import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'fr' | 'en' | 'es';

const SUPPORTED_LANGUAGES: Language[] = ['fr', 'en', 'es'];

function detectDeviceLanguage(): Language {
  try {
    const browserLang = navigator.language || (navigator as any).userLanguage || 'fr';
    const langCode = browserLang.split('-')[0].toLowerCase();
    if (SUPPORTED_LANGUAGES.includes(langCode as Language)) {
      return langCode as Language;
    }
    return 'en';
  } catch {
    return 'fr';
  }
}

function isFirstLaunch(): boolean {
  try {
    const stored = localStorage.getItem('lucky-stop-language');
    return !stored;
  } catch {
    return true;
  }
}

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
}

const initialLanguage = isFirstLaunch() ? detectDeviceLanguage() : 'fr';

export const useLanguage = create<LanguageState>()(
  persist(
    (set) => ({
      language: initialLanguage,
      setLanguage: (language) => set({ language }),
    }),
    {
      name: 'lucky-stop-language',
    }
  )
);

export const translations = {
  fr: {
    // Main Menu
    title: 'LUCKY STOP',
    subtitle: 'Tapez dans la zone verte au bon moment!',
    bestScore: 'Meilleur Score',
    coins: 'Coins',
    playNow: 'JOUER MAINTENANT',
    gameModes: 'MODES DE JEU',
    shop: 'BOUTIQUE',
    dailyChallenges: 'DÉFIS QUOTIDIENS',
    onlineLeaderboard: 'CLASSEMENT EN LIGNE',
    theme: 'Thème',
    mode: 'Mode',
    trapWarning: '⚠️ Attention : une des zones est un piège. Choisis bien…',
    avoidTrap: 'Évite la zone piégée !',
    trapZone: 'Zone traîtresse !',
    gifts: 'Cadeaux',
    language: 'Langue',
    new: 'Nouveau',
    news: 'Actualité',
    contest: 'Concours',
    newsAndContest: 'Actualité et Concours',
    comingSoon: 'Coming Soon',
    comingSoonDesc: 'De nouvelles fonctionnalités arrivent bientôt ! 🚀',
    inventory: 'Inventaire',
    // Settings
    settings: 'Réglages',
    sound: 'Son',
    dailyNotifications: 'Notifications quotidiennes',
    notificationDesc: 'Une notification par jour car le classement n\'attend que toi 🎮',
    close: 'Fermer',
    // Social
    joinUs: 'Rejoins-nous !',
    socialDesc: 'Suis l\'actualité et participe au prochain concours pour gagner des récompenses exclusives ! 🎁',
    // Leaderboard
    back: 'Retour',
    backToMenu: 'Retour au Menu',
    username: 'Pseudo',
    noUsername: 'Aucun pseudo',
    global: 'Global',
    weekly: 'Hebdomadaire',
    refresh: 'Actualiser',
    offlineMode: 'Mode hors ligne - Reconnectez-vous pour voir le classement',
    noScores: 'Aucun score enregistré pour ce mode',
    beFirst: 'Sois le premier à jouer !',
    noWeeklyScores: 'Aucun score cette semaine pour ce mode',
    beFirstWeek: 'Sois le premier à jouer cette semaine !',
    usernameChanged: 'Pseudo modifié',
    usernameChangedDesc: 'Votre nouveau pseudo a été sauvegardé',
    networkError: 'Erreur réseau',
    networkErrorDesc: 'Impossible de charger le classement',
    // Shop
    shopTitle: 'BOUTIQUE',
    shopDesc: 'Débloquez des thèmes, modes de jeux et boosts',
    themes: 'Thèmes',
    modes: 'Modes de jeux',
    boosts: 'Boosts',
    equipped: 'Équipé',
    owned: 'Possédé',
    locked: 'Verrouillé',
    unlock: 'Débloquer',
    buy: 'Acheter',
    insufficientCoins: 'Coins insuffisants',
    insufficientCoinsDesc: 'Il te faut {amount} coins pour acheter ceci.',
    themeLocked: 'Thème verrouillé',
    themeLockedDesc: 'Complétez 7 jours de récompenses quotidiennes pour débloquer ce thème exclusif !',
    packBought: 'Pack acheté !',
    packBoughtDesc: 'Tu as reçu 4 tickets pour le mode Expert !',
    ticketPack: 'Pack de Tickets Expert',
    ticketPackDesc: '4 tickets pour jouer au mode Mémoire (Expert). 1 ticket = 1 partie.',
    freeCoinsAd: 'Regarder une pub (80 Coins)',
    watchAdAndGet: 'Regarde une pub et obtiens {amount} Coins gratuitement !',
    adCooldown: 'Nouvelle pub dans {time}',
    boostShopEmpty: 'Les boosts s\'obtiennent via les défis et récompenses quotidiennes !',
    checkChallenges: 'Voir les Défis',
    currentTheme: 'Thème Actuel',
    equip: 'Équiper',
    lockedDays: 'Verrouillé - 7 jours requis',
    unlock7Days: 'Complétez 7 jours de récompenses quotidiennes pour débloquer ce thème légendaire !',
    buyCoins: 'Acheter ({price} coins)',
    currentTickets: 'Tickets actuels:',
    price: 'Prix:',
    buy4Tickets: 'Acheter 4 tickets ({price} coins)',
    get5ByAd: 'Obtenir 5 via pub',
    ticketsReceived: 'Tickets reçus !',
    ticketsReceivedDesc: 'Tu as reçu 5 tickets ! 🎫',
    modeUnlocked: 'Mode Débloqué',
    unlockMode: 'Débloquer ({price} coins)',
    earnCoinsFooter: 'Gagnez des coins en jouant pour débloquer de nouveaux thèmes !',
    ownedCount: 'Possédés: {count}',
    boostBought: 'Boost acheté !',
    boostBoughtDesc: 'Tu as acheté un boost {name}.',
    buyFor: 'Acheter pour {price} coins',
    getByAd: 'Obtenir via pub',
    boostReceived: 'Boost reçu !',
    boostReceivedDesc: 'Tu as reçu {name} {icon}',
    // Challenges
    challengesTitle: 'DÉFIS DE PROGRESSION',
    challengeProgress: 'Progression des défis',
    totalGamesPlayed: 'Total de parties jouées',
    claimRewards: 'Réclamer {count} boost(s)',
    reward: 'Récompense',
    randomBoost: '1 boost aléatoire',
    score: 'Score',
    level: 'Niveau',
    challengeInfo1: 'Chaque mode a 10 paliers de progression (10, 20, 30... jusqu\'à 100 points)',
    challengeInfo2: 'Atteignez les paliers pour gagner des coins',
    challengeInfo3: 'Débloquez des boosts en jouant des parties (tous modes confondus)',
    rewardClaimed: 'Récompense réclamée !',
    coinsReceived: '{amount} coins ajoutés à votre compte',
    boostsClaimed: 'Boost(s) réclamé(s) !',
    boostsAdded: '{boosts} ajouté(s) à votre inventaire',
    challengeCompleted: 'Palier atteint ! 🎉',
    challengeCompletedDesc: '{mode} - Score de {score} atteint ! Réclamez votre récompense dans les Défis.',
    gamesPlayedReward: '{count} parties jouées ! Réclamez votre boost dans les Défis.',
    challenges: 'Défis',
    daily: 'Quotidiens',
    globalChallenges: 'Globaux',
    dailyChallengesHeader: 'Défis du jour',
    dailyChallengesSubtitle: '3 nouveaux défis chaque jour',
    claim: 'Réclamer',
    howItWorks: 'Comment ça marche ?',
    howItWorksGames: 'Parties jouées (∞) : toutes les 50 parties → 1 boost.',
    howItWorksModes: 'Défis par mode : paliers de score 10 → 100. Chaque palier atteint débloque des coins à réclamer (10, 20, 30...).',
    howItWorksRewards: 'Les récompenses restent en attente jusqu\'à réclamation.',
    games: 'parties',
    gamesPlayed: 'Parties jouées',
    tier: 'Palier',
    boostReward: '+1 boost',
    completed: 'Complété',
    done: '✓ Terminé',
    tierUnlocked: 'palier(s) débloqué(s) !',
    gamesPlayedTierUnlocked: 'palier(s) Parties débloqué(s) !',
    added: 'ajouté(s) !',
    // Modes
    modeSelectionTitle: 'SÉLECTION DU MODE',
    currentMode: 'Mode actuel',
    gameInProgress: 'Partie en cours',
    gameInProgressDesc: 'Termine ta partie actuelle pour changer de mode.',
    selectMode: 'Choisir ce Mode',
    playNowMode: 'Jouer maintenant',
    buyInShop: 'Acheter en Boutique',
    duration: 'Durée',
    variableArc: 'Arc variable',
    mobileZone: 'Zone mobile',
    bestScoreMode: 'Meilleur Score',
    modeInfo: 'Les meilleurs scores sont sauvegardés séparément pour chaque mode',
    bonusAvailable: 'Bonus x2 disponible',
    bonusActive: 'x2 actif',
    bonusX2: 'Bonus x2',
    nextDrawIn: 'Prochain tirage dans',
    x2Coins: 'x2 COINS',
    bestScoreLabel: 'Meilleur Score:',
    // Mode names
    modeClassic: 'Classique',
    modeArcChangeant: 'Arc changeant',
    modeSurvie30s: 'Survie 30s',
    modeZoneMobile: 'Zone mobile',
    modeZoneTraitresse: 'Zone traîtresse',
    modeMemoireExpert: 'Mémoire (Expert)',
    // Mode descriptions
    descClassic: 'Le mode de jeu original. L\'arc reste fixe, +3% de vitesse par réussite.',
    descArcChangeant: 'À chaque réussite, l\'arc vert change de taille et d\'emplacement. +3% de vitesse.',
    descSurvie30s: 'Tu as 30 secondes pour réussir le plus de hits. Un échec = game over !',
    descZoneMobile: 'L\'arc vert glisse en continu autour du cercle. +3% de vitesse à chaque réussite.',
    descZoneTraitresse: 'Plusieurs zones vertes, mais une seule est piégée. Trouve la bonne zone pour gagner !',
    descMemoireExpert: 'Une zone verte apparaît 1 seconde, mémorise sa position et clique au bon endroit ! La difficulté augmente à chaque niveau.',
    // Daily Rewards
    dailyRewardsTitle: 'RÉCOMPENSES QUOTIDIENNES',
    yourStreak: 'Ta Série',
    day: 'Jour',
    days: 'jours',
    consecutiveDays: 'jours consécutifs',
    claimReward: 'Récupérer',
    comeBackTomorrow: 'Reviens demain',
    watchAdForCoins: 'Regarder une pub pour {amount} Coins',
    watchAdDesc: 'Regarde une pub et obtiens {amount} Coins gratuitement !',
    coinsReceivedTitle: 'Coins reçus !',
    coinsReceivedDesc: 'Tu as reçu {amount} coins ! 🪙',
    rewardClaimedDaily: 'Récompense réclamée ! 🎉',
    rewardClaimedDailyDesc: 'Tu as reçu : {reward}',
    cooldownInfo: 'Reviens demain pour continuer ta série !',
    dailyRewardsHeader: 'Récompenses Journalières',
    currentStreak: 'Série actuelle:',
    dayShort: 'J',
    themeReward: 'Thème',
    boostRewardLabel: 'Boost',
    rewardAvailable: 'Récompense disponible !',
    dayLabel: 'Jour {day}:',
    exclusiveTheme: '{coins} coins + Thème Exclusif',
    claimRewardBtn: 'Récupérer',
    rewardClaimed2: '🎉 Récompense récupérée !',
    royalTheme: '{coins} coins + Thème Royal',
    comeBackTomorrowReward: 'Reviens demain pour ta prochaine récompense !',
    notifBonus: 'Bonus Notifications',
    notifBonusAmount: '+20 coins/jour',
    notifBonusDesc: 'Active les notifications dans les réglages pour recevoir 20 coins bonus chaque jour !',
    claimNotifBonus: 'Récupérer +20 coins',
    notifBonusClaimed: '✓ Bonus déjà récupéré aujourd\'hui',
    notifBonusLocked: 'Active les notifications dans les réglages pour débloquer',
    adBonus: 'Bonus Publicité',
    adBonusAmount: '+100 coins',
    adBonusDesc: 'Regarde une pub et gagne 100 coins !',
    watchAd: 'Regarder une pub',
    notifBonusTitle: 'Bonus Notifications !',
    notifBonusToast: '+20 coins pour avoir activé les notifications ! 🔔',
    // Customization
    customizationTitle: 'PERSONNALISATION',
    apply: 'Appliquer',
    colorPalettes: '🎨 Palettes de couleurs',
    circles: '⭕ Cercles',
    effects: '✨ Effets',
    // Game
    combo: 'Combo',
    perfect: 'PARFAIT',
    great: 'EXCELLENT',
    good: 'BIEN',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'Appuie pour commencer !',
    tapToPlay: 'TAPE !',
    gameOver: 'GAME OVER',
    finalScore: 'Score final',
    newRecord: 'NOUVEAU RECORD !',
    restart: 'Rejouer',
    mainMenu: 'Menu Principal',
    revive: 'Revivre',
    watchAdRevive: 'Regarder une pub',
    reviveSuccess: 'Partie relancée ! 🎮',
    reviveSuccessDesc: 'Tu peux continuer à jouer !',
    selectBoosts: 'Sélectionner des Boosts',
    availableBoosts: 'Boosts Disponibles',
    selectedBoosts: 'Boosts Sélectionnés',
    noBoostsAvailable: 'Aucun boost disponible',
    startWithBoosts: 'Commencer avec {count} boost(s)',
    shield: 'Bouclier',
    shieldDesc: 'Première erreur pardonnée',
    biggerZone: 'Zone agrandie',
    biggerZoneDesc: 'Zone de succès +50% plus grande',
    start20: 'Départ +20',
    start20Desc: 'Commence avec 20 points',
    needTicket: 'Il faut 1 ticket pour jouer à ce mode',
    ticketsRemaining: '{count} ticket(s) restant(s)',
    // Online Leaderboards
    weeklyRankings: 'Classements Hebdomadaires',
    leaderboardTitle: 'CLASSEMENT MONDIAL',
    leaderboardDesc: 'Compare ton score avec les meilleurs joueurs',
    yourRank: 'Ton Rang',
    notRanked: 'Non classé',
    rank: 'Rang',
    player: 'Joueur',
    modeLabel: 'Mode',
    selectModeLeaderboard: 'Sélectionner un mode',
    selectModeDesc: 'Choisis un mode pour voir le classement',
    noScoresYet: 'Aucun score pour l\'instant',
    noScoresYetDesc: 'Sois le premier à établir un record !',
    loadingScores: 'Chargement des scores...',
    errorLoading: 'Erreur de chargement',
    errorLoadingDesc: 'Impossible de charger le classement',
    newRankingIn: 'Nouveau classement dans',
    // Ad Reward Dialog
    freeCoins: 'Coins Gratuits',
    watchAdDialogDesc: 'Regarde une courte publicité et gagne des coins gratuitement !',
    coinsToWin: 'Coins à gagner',
    adPlaying: 'Publicité en cours...',
    pleaseWait: 'Merci de patienter quelques secondes',
    adTip: '💡 Astuce : Regarde des pubs régulièrement pour maximiser tes gains !',
    coinsReceivedAd: 'Coins reçus !',
    coinsReceivedAdDesc: 'Tu as reçu 100 coins ! 🪙',
    // Game UI (CircleTap)
    menu: 'Menu',
    best: 'Meilleur',
    levelLabel: 'Niveau',
    gameOverLabel: 'PARTIE TERMINÉE',
    ticket: 'ticket',
    tickets: 'tickets',
    play: 'JOUER',
    restartLabel: 'RECOMMENCER',
    reviveLabel: 'REVIVE',
    noTicket: 'Pas de ticket !',
    noTicketDesc: 'Achète des tickets dans la boutique pour jouer au mode Expert.',
    reviveUsed: 'Revive déjà utilisé',
    reviveUsedDesc: 'Tu ne peux revivre qu\'une seule fois par partie.',
    reviveActivated: 'Revive activé !',
    reviveActivatedDesc: 'Tu as été ramené à la vie !',
    reviveByAd: 'Revivre via pub',
    tapOnScreen: 'Tape sur l\'écran',
    tapInGreenZone: 'Tapez quand la barre est dans la zone verte!',
    tapToStartGame: 'Tapez sur l\'écran pour commencer ou appuyez sur ESPACE/ENTRÉE',
    speedLabel: 'Vitesse',
    zoneLabel: 'Zone',
    // Boost Menus
    buyBoostsShop: 'Achète des boosts dans la boutique pour les utiliser !',
    selectBoostsNext: 'Sélectionne les boosts pour ta prochaine partie :',
    unavailableMode: 'Indisponible pour ce mode',
    restartGameLabel: 'RELANCER LA PARTIE',
    prepareGame: 'Prépare ta partie',
    startWithoutBoost: 'Commencer sans boost',
    selectBoostsUse: 'Sélectionne les boosts que tu veux utiliser :',
    startGameLabel: 'COMMENCER LA PARTIE',
    // Username Modal
    chooseUsername: 'Choisir un pseudo',
    useInstagram: '📸 Utilise ton pseudo Instagram !',
    contestsSoon: 'Des concours et récompenses arrivent bientôt 🎁',
    usernameLabel: 'Pseudo (3-16 caractères)',
    usernamePlaceholder: 'ton_pseudo_insta',
    usernameRules: 'Lettres, chiffres et underscore uniquement',
    random: 'Aléatoire',
    validateLabel: 'Valider',
    importantConfirmation: '⚠️ Confirmation importante',
    aboutToRegister: 'Tu es sur le point d\'enregistrer le pseudo :',
    importantNote: 'Important :',
    dontChangeUsername: 'Il est fortement recommandé de ne plus changer ton pseudo après validation pour éviter tout problème de synchronisation dans le classement.',
    ensureInstagram: 'Assure-toi que c\'est bien ton pseudo Instagram si tu veux participer aux futurs concours !',
    modify: 'Modifier',
    confirmLabel: 'Confirmer',
    usernameRegistered: '✅ Pseudo enregistré',
    usernameRegisteredDesc: 'Ton pseudo a été enregistré avec succès !',
    usernameError: 'Le pseudo doit contenir entre 3 et 16 caractères (lettres, chiffres, underscore)',
    usernameSaveError: 'Erreur lors de la sauvegarde du pseudo',
    usernameSameAsCurrent: 'Ce pseudo est déjà le tien',
    usernameChangeLimitReached: 'Tu as atteint la limite de changements de pseudo (2 max)',
    usernameChangesRemaining: '{count} changement(s) restant(s)',
    usernameNoChangesLeft: 'Tu ne peux plus changer de pseudo',
    usernameChangeWarning: 'Après cette confirmation, il te restera {count} changement(s) de pseudo.',
    usernameFirstTimeNote: 'Tu pourras changer ton pseudo 2 fois maximum après cette première inscription.',
    // Submit Score Modal
    submitScoreLabel: 'Soumettre ton score',
    submitError: 'Erreur lors de la soumission',
    serverUnavailable: 'Serveur indisponible, réessaie plus tard',
    scoreSubmitted: 'Score soumis avec succès ✅',
    classic: 'Classique',
    arcChangeant: 'Arc Changeant',
    survie60s: 'Survie 30s',
    zoneMobile: 'Zone Mobile',
    sending: 'Envoi...',
    submitBtn: 'Soumettre',
    cancel: 'Annuler',
    // Weekly Timer
    newLeaderboard: 'Nouveau classement dans:',
    daysShort: 'j',
    saveError: 'Erreur lors de la sauvegarde du pseudo',
    // Notifications Test
    testNotification: 'Tester les notifications',
    testBtn: 'Test',
    testNotificationSent: 'Notification envoyée !',
    testNotificationSentDesc: 'Vérifie tes notifications.',
    testNotificationFailed: 'Échec',
    testNotificationFailedDesc: 'Autorise les notifications d\'abord.',
    // Lucky Wheel
    luckyWheelTitle: 'Roue de la Chance',
    freeSpin: 'Tour Gratuit !',
    watchAdToSpin: 'Pub pour tourner',
    youWon: 'Tu as gagné :',
    wheelReady: 'Roue prête !',
    wheelReadyDesc: 'Viens tourner la roue de la chance ! 🎡',
    // Season Pass
    seasonPass: 'Pass de Saison',
    seasonPassShort: 'Pass',
    seasonLabel: 'Saison',
    watchArrow: 'Regarder →',
    dailyQuests: 'Quêtes du jour',
    dailyQuestsReward: '+1 💎 les 2 complétées',
    quest1Title: 'Score de 20+ dans une partie',
    quest1Subtitle: 'N\'importe quel mode',
    quest2Title: 'Utiliser un boost en jeu',
    quest2Subtitle: 'N\'importe quel boost ou mode',
    claimDiamond: 'Récupérer 1 💎',
    questRewardClaimed: 'Récompense récupérée aujourd\'hui !',
    questsCompleted: '{count}/2 quêtes complétées',
    tiersToUnlock: 'Paliers à débloquer',
    unlocked: 'Débloqué',
    pulsedUsername: 'TonPseudo pulsé',
    violetUsername: 'TonPseudo en violet',
    diamondObtained: '💎 Diamant obtenu !',
    diamondObtainedDesc: 'Tu as gagné 1 diamant en complétant les 2 quêtes !',
    decoUnlocked: '🎉 Décoration débloquée !',
    decoUnlockedDesc: 'Tu as débloqué "{name}" !',
    diamondBought: '💎 Diamant acheté !',
    diamondBoughtDesc: '1 coin → 1 diamant',
    diamondByAd: '💎 Diamant obtenu !',
    diamondByAdDesc: 'Tu as gagné 1 diamant en regardant une pub !',
    // Slot Machine
    dailyBonus: 'Bonus Quotidien',
    slotDescription: 'Lance la machine pour doubler tes coins dans un mode pendant 24h',
    spinInProgress: 'Tirage en cours…',
    launchSpin: 'Lancer le tirage',
    activeUntilMidnight: 'Actif jusqu\'à minuit',
    bonusAlreadyActive: 'Bonus déjà activé aujourd\'hui',
    // Inventory
    inventoryTitle: 'Inventaire',
    diamonds: 'Diamants',
    items: 'Objets',
    decorations: 'Décorations',
    leaderboardPreview: 'Aperçu dans le classement',
    playToApply: '⚡ Joue une partie pour appliquer les changements',
    removeDecoration: 'Retirer la décoration',
    selectDecoration: 'Sélectionne une décoration ci-dessous',
    usernameColor: 'Couleur du pseudo',
    defaultColor: 'Défaut',
    violet: 'Violet',
    pulsed: 'Pulsé',
    ticketItem: 'Ticket Partie',
    ticketItemDesc: 'Permet de jouer sur les modes premium',
    modeTickets: 'Tickets de mode',
    unlockedDecos: '{unlocked} / {total} débloquée(s)',
    usernameTooShort: 'Pseudo trop court',
    usernameTooShortDesc: 'Minimum 3 caractères.',
    usernameTooLong: 'Pseudo trop long',
    usernameTooLongDesc: 'Maximum 20 caractères.',
    usernameTaken: 'Pseudo déjà pris',
    usernameTakenDesc: 'Choisis un autre pseudo.',
    usernameUpdated: '✅ Pseudo mis à jour !',
    usernameUpdatedDesc: 'Ton pseudo est maintenant "{name}".',
    // Daily Challenges (data)
    classicBeginner: 'Classique Débutant',
    classicBeginnerDesc: 'Fais un score de 10 en Classique',
    classicApprentice: 'Classique Apprenti',
    classicApprenticeDesc: 'Fais un score de 15 en Classique',
    classicConfirmed: 'Classique Confirmé',
    classicConfirmedDesc: 'Fais un score de 20 en Classique',
    classicPro: 'Classique Pro',
    classicProDesc: 'Fais un score de 25 en Classique',
    arcBeginner: 'Arc Débutant',
    arcBeginnerDesc: 'Fais un score de 8 en Arc changeant',
    arcIntermediate: 'Arc Intermédiaire',
    arcIntermediateDesc: 'Fais un score de 12 en Arc changeant',
    arcConfirmed: 'Arc Confirmé',
    arcConfirmedDesc: 'Fais un score de 15 en Arc changeant',
    arcExpert: 'Arc Expert',
    arcExpertDesc: 'Fais un score de 20 en Arc changeant',
    survivalBeginner: 'Survivant Débutant',
    survivalBeginnerDesc: 'Fais un score de 5 en Survie 30s',
    survivor: 'Survivant',
    survivorDesc: 'Fais un score de 8 en Survie 30s',
    survivalConfirmed: 'Survie Confirmé',
    survivalConfirmedDesc: 'Fais un score de 12 en Survie 30s',
    survivalMaster: 'Maître Survie',
    survivalMasterDesc: 'Fais un score de 15 en Survie 30s',
    mobileNomad: 'Zone Nomade',
    mobileNomadDesc: 'Fais un score de 8 en Zone mobile',
    mobileHunter: 'Chasseur Mobile',
    mobileHunterDesc: 'Fais un score de 12 en Zone mobile',
    mobileConfirmed: 'Mobile Confirmé',
    mobileConfirmedDesc: 'Fais un score de 15 en Zone mobile',
    mobileExpert: 'Expert Mobile',
    mobileExpertDesc: 'Fais un score de 20 en Zone mobile',
    detector: 'Détecteur',
    detectorDesc: 'Fais un score de 5 en Zone traîtresse',
    minesweeper: 'Démineur',
    minesweeperDesc: 'Fais un score de 8 en Zone traîtresse',
    trapConfirmed: 'Traîtresse Confirmé',
    trapConfirmedDesc: 'Fais un score de 10 en Zone traîtresse',
    trapExpert: 'Expert Démineur',
    trapExpertDesc: 'Fais un score de 15 en Zone traîtresse',
    shortMemory: 'Mémoire courte',
    shortMemoryDesc: 'Fais un score de 3 en Mémoire Expert',
    goodMemory: 'Bonne mémoire',
    goodMemoryDesc: 'Fais un score de 5 en Mémoire Expert',
    memoryConfirmed: 'Mémoire Confirmé',
    memoryConfirmedDesc: 'Fais un score de 8 en Mémoire Expert',
    eidetic: 'Mémoire eidétique',
    eideticDesc: 'Fais un score de 10 en Mémoire Expert',
  },
  en: {
    title: 'LUCKY STOP',
    subtitle: 'Tap in the green zone at the right time!',
    bestScore: 'Best Score',
    coins: 'Coins',
    playNow: 'PLAY NOW',
    gameModes: 'GAME MODES',
    shop: 'SHOP',
    dailyChallenges: 'DAILY CHALLENGES',
    onlineLeaderboard: 'ONLINE LEADERBOARD',
    theme: 'Theme',
    mode: 'Mode',
    trapWarning: '⚠️ Warning: one of the zones is a trap. Choose wisely…',
    avoidTrap: 'Avoid the trap zone!',
    trapZone: 'Trap zone!',
    gifts: 'Gifts',
    language: 'Language',
    new: 'New',
    news: 'News',
    contest: 'Contest',
    newsAndContest: 'News and Contest',
    comingSoon: 'Coming Soon',
    comingSoonDesc: 'New features coming soon! 🚀',
    inventory: 'Inventory',
    settings: 'Settings',
    sound: 'Sound',
    dailyNotifications: 'Daily Notifications',
    notificationDesc: 'One notification per day because the leaderboard is waiting for you 🎮',
    close: 'Close',
    joinUs: 'Join Us!',
    socialDesc: 'Follow the news and participate in the next contest to win exclusive rewards! 🎁',
    back: 'Back',
    backToMenu: 'Back to Menu',
    username: 'Username',
    noUsername: 'No username',
    global: 'Global',
    weekly: 'Weekly',
    refresh: 'Refresh',
    offlineMode: 'Offline mode - Reconnect to see the leaderboard',
    noScores: 'No scores recorded for this mode',
    beFirst: 'Be the first to play!',
    noWeeklyScores: 'No scores this week for this mode',
    beFirstWeek: 'Be the first to play this week!',
    usernameChanged: 'Username changed',
    usernameChangedDesc: 'Your new username has been saved',
    networkError: 'Network error',
    networkErrorDesc: 'Unable to load leaderboard',
    shopTitle: 'SHOP',
    shopDesc: 'Unlock themes, game modes and boosts',
    themes: 'Themes',
    modes: 'Game Modes',
    boosts: 'Boosts',
    equipped: 'Equipped',
    owned: 'Owned',
    locked: 'Locked',
    unlock: 'Unlock',
    buy: 'Buy',
    insufficientCoins: 'Insufficient Coins',
    insufficientCoinsDesc: 'You need {amount} coins to buy this.',
    themeLocked: 'Theme Locked',
    themeLockedDesc: 'Complete 7 days of daily rewards to unlock this exclusive theme!',
    packBought: 'Pack Purchased!',
    packBoughtDesc: 'You received 4 tickets for Expert mode!',
    ticketPack: 'Expert Tickets Pack',
    ticketPackDesc: '4 tickets to play Memory (Expert) mode. 1 ticket = 1 game.',
    freeCoinsAd: 'Watch Ad (80 Coins)',
    watchAdAndGet: 'Watch an ad and get {amount} Coins for free!',
    adCooldown: 'New ad in {time}',
    boostShopEmpty: 'Boosts are obtained through challenges and daily rewards!',
    checkChallenges: 'View Challenges',
    currentTheme: 'Current Theme',
    equip: 'Equip',
    lockedDays: 'Locked - 7 days required',
    unlock7Days: 'Complete 7 days of daily rewards to unlock this legendary theme!',
    buyCoins: 'Buy ({price} coins)',
    currentTickets: 'Current tickets:',
    price: 'Price:',
    buy4Tickets: 'Buy 4 tickets ({price} coins)',
    get5ByAd: 'Get 5 via ad',
    ticketsReceived: 'Tickets received!',
    ticketsReceivedDesc: 'You received 5 tickets! 🎫',
    modeUnlocked: 'Mode Unlocked',
    unlockMode: 'Unlock ({price} coins)',
    earnCoinsFooter: 'Earn coins by playing to unlock new themes!',
    ownedCount: 'Owned: {count}',
    boostBought: 'Boost purchased!',
    boostBoughtDesc: 'You bought a {name} boost.',
    buyFor: 'Buy for {price} coins',
    getByAd: 'Get via ad',
    boostReceived: 'Boost received!',
    boostReceivedDesc: 'You received {name} {icon}',
    challengesTitle: 'PROGRESSION CHALLENGES',
    challengeProgress: 'Challenge progress',
    totalGamesPlayed: 'Total games played',
    claimRewards: 'Claim {count} boost(s)',
    reward: 'Reward',
    randomBoost: '1 random boost',
    score: 'Score',
    level: 'Level',
    challengeInfo1: 'Each mode has 10 progression tiers (10, 20, 30... up to 100 points)',
    challengeInfo2: 'Reach tiers to earn coins',
    challengeInfo3: 'Unlock boosts by playing games (all modes combined)',
    rewardClaimed: 'Reward Claimed!',
    coinsReceived: '{amount} coins added to your account',
    boostsClaimed: 'Boost(s) Claimed!',
    boostsAdded: '{boosts} added to your inventory',
    challengeCompleted: 'Tier Reached! 🎉',
    challengeCompletedDesc: '{mode} - Score of {score} reached! Claim your reward in Challenges.',
    gamesPlayedReward: '{count} games played! Claim your boost in Challenges.',
    challenges: 'Challenges',
    daily: 'Daily',
    globalChallenges: 'Global',
    dailyChallengesHeader: 'Daily Challenges',
    dailyChallengesSubtitle: '3 new challenges every day',
    claim: 'Claim',
    howItWorks: 'How does it work?',
    howItWorksGames: 'Games played (∞): every 50 games → 1 boost.',
    howItWorksModes: 'Mode challenges: score tiers 10 → 100. Each tier reached unlocks coins to claim (10, 20, 30...).',
    howItWorksRewards: 'Rewards stay pending until claimed.',
    games: 'games',
    gamesPlayed: 'Games played',
    tier: 'Tier',
    boostReward: '+1 boost',
    completed: 'Completed',
    done: '✓ Completed',
    tierUnlocked: 'tier(s) unlocked!',
    gamesPlayedTierUnlocked: 'Games tier(s) unlocked!',
    added: 'added!',
    modeSelectionTitle: 'MODE SELECTION',
    currentMode: 'Current Mode',
    gameInProgress: 'Game in Progress',
    gameInProgressDesc: 'Finish your current game to change mode.',
    selectMode: 'Choose This Mode',
    playNowMode: 'Play Now',
    buyInShop: 'Buy in Shop',
    duration: 'Duration',
    variableArc: 'Variable arc',
    mobileZone: 'Mobile zone',
    bestScoreMode: 'Best Score',
    modeInfo: 'Best scores are saved separately for each mode',
    bonusAvailable: 'x2 Bonus available',
    bonusActive: 'x2 active',
    bonusX2: 'x2 Bonus',
    nextDrawIn: 'Next draw in',
    x2Coins: 'x2 COINS',
    bestScoreLabel: 'Best Score:',
    modeClassic: 'Classic',
    modeArcChangeant: 'Changing Arc',
    modeSurvie30s: 'Survival 30s',
    modeZoneMobile: 'Mobile Zone',
    modeZoneTraitresse: 'Trap Zone',
    modeMemoireExpert: 'Memory (Expert)',
    descClassic: 'The original game mode. The arc stays fixed, +3% speed per success.',
    descArcChangeant: 'After each success, the green arc changes size and position. +3% speed.',
    descSurvie30s: 'You have 30 seconds to score as many hits as possible. A miss = game over!',
    descZoneMobile: 'The green arc slides continuously around the circle. +3% speed per success.',
    descZoneTraitresse: 'Multiple green zones, but one is trapped. Find the right zone to win!',
    descMemoireExpert: 'A green zone appears for 1 second, memorize its position and click in the right spot! Difficulty increases at each level.',
    dailyRewardsTitle: 'DAILY REWARDS',
    yourStreak: 'Your Streak',
    day: 'Day',
    days: 'days',
    consecutiveDays: 'consecutive days',
    claimReward: 'Claim',
    comeBackTomorrow: 'Come back tomorrow',
    watchAdForCoins: 'Watch Ad for {amount} Coins',
    watchAdDesc: 'Watch an ad and get {amount} Coins for free!',
    coinsReceivedTitle: 'Coins Received!',
    coinsReceivedDesc: 'You received {amount} coins! 🪙',
    rewardClaimedDaily: 'Reward Claimed! 🎉',
    rewardClaimedDailyDesc: 'You received: {reward}',
    cooldownInfo: 'Come back tomorrow to continue your streak!',
    dailyRewardsHeader: 'Daily Rewards',
    currentStreak: 'Current streak:',
    dayShort: 'D',
    themeReward: 'Theme',
    boostRewardLabel: 'Boost',
    rewardAvailable: 'Reward available!',
    dayLabel: 'Day {day}:',
    exclusiveTheme: '{coins} coins + Exclusive Theme',
    claimRewardBtn: 'Claim',
    rewardClaimed2: '🎉 Reward claimed!',
    royalTheme: '{coins} coins + Royal Theme',
    comeBackTomorrowReward: 'Come back tomorrow for your next reward!',
    notifBonus: 'Notification Bonus',
    notifBonusAmount: '+20 coins/day',
    notifBonusDesc: 'Enable notifications in settings to receive 20 bonus coins every day!',
    claimNotifBonus: 'Claim +20 coins',
    notifBonusClaimed: '✓ Bonus already claimed today',
    notifBonusLocked: 'Enable notifications in settings to unlock',
    adBonus: 'Ad Bonus',
    adBonusAmount: '+100 coins',
    adBonusDesc: 'Watch an ad and earn 100 coins!',
    watchAd: 'Watch an ad',
    notifBonusTitle: 'Notification Bonus!',
    notifBonusToast: '+20 coins for enabling notifications! 🔔',
    customizationTitle: 'CUSTOMIZATION',
    apply: 'Apply',
    colorPalettes: '🎨 Color Palettes',
    circles: '⭕ Circles',
    effects: '✨ Effects',
    combo: 'Combo',
    perfect: 'PERFECT',
    great: 'GREAT',
    good: 'GOOD',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'Tap to start!',
    tapToPlay: 'TAP!',
    gameOver: 'GAME OVER',
    finalScore: 'Final Score',
    newRecord: 'NEW RECORD!',
    restart: 'Play Again',
    mainMenu: 'Main Menu',
    revive: 'Revive',
    watchAdRevive: 'Watch Ad',
    reviveSuccess: 'Game Revived! 🎮',
    reviveSuccessDesc: 'You can continue playing!',
    selectBoosts: 'Select Boosts',
    availableBoosts: 'Available Boosts',
    selectedBoosts: 'Selected Boosts',
    noBoostsAvailable: 'No boosts available',
    startWithBoosts: 'Start with {count} boost(s)',
    shield: 'Shield',
    shieldDesc: 'First mistake forgiven',
    biggerZone: 'Bigger Zone',
    biggerZoneDesc: 'Success zone +50% larger',
    start20: 'Start +20',
    start20Desc: 'Start with 20 points',
    needTicket: 'Need 1 ticket to play this mode',
    ticketsRemaining: '{count} ticket(s) remaining',
    weeklyRankings: 'Weekly Rankings',
    leaderboardTitle: 'WORLD RANKINGS',
    leaderboardDesc: 'Compare your score with the best players',
    yourRank: 'Your Rank',
    notRanked: 'Not ranked',
    rank: 'Rank',
    player: 'Player',
    modeLabel: 'Mode',
    selectModeLeaderboard: 'Select a mode',
    selectModeDesc: 'Choose a mode to see rankings',
    noScoresYet: 'No scores yet',
    noScoresYetDesc: 'Be the first to set a record!',
    loadingScores: 'Loading scores...',
    errorLoading: 'Loading error',
    errorLoadingDesc: 'Unable to load leaderboard',
    newRankingIn: 'New ranking in',
    freeCoins: 'Free Coins',
    watchAdDialogDesc: 'Watch a short ad and get coins for free!',
    coinsToWin: 'Coins to win',
    adPlaying: 'Ad playing...',
    pleaseWait: 'Please wait a few seconds',
    adTip: '💡 Tip: Watch ads regularly to maximize your earnings!',
    coinsReceivedAd: 'Coins Received!',
    coinsReceivedAdDesc: 'You received 100 coins! 🪙',
    menu: 'Menu',
    best: 'Best',
    levelLabel: 'Level',
    gameOverLabel: 'GAME OVER',
    ticket: 'ticket',
    tickets: 'tickets',
    play: 'PLAY',
    restartLabel: 'RESTART',
    reviveLabel: 'REVIVE',
    noTicket: 'No ticket!',
    noTicketDesc: 'Buy tickets in the shop to play Expert mode.',
    reviveUsed: 'Revive already used',
    reviveUsedDesc: 'You can only revive once per game.',
    reviveActivated: 'Revive activated!',
    reviveActivatedDesc: 'You\'ve been brought back to life!',
    reviveByAd: 'Revive via ad',
    tapOnScreen: 'Tap the screen',
    tapInGreenZone: 'Tap when the bar is in the green zone!',
    tapToStartGame: 'Tap the screen to start or press SPACE/ENTER',
    speedLabel: 'Speed',
    zoneLabel: 'Zone',
    buyBoostsShop: 'Buy boosts in the shop to use them!',
    selectBoostsNext: 'Select boosts for your next game:',
    unavailableMode: 'Unavailable for this mode',
    restartGameLabel: 'RESTART GAME',
    prepareGame: 'Prepare your game',
    startWithoutBoost: 'Start without boost',
    selectBoostsUse: 'Select boosts to use:',
    startGameLabel: 'START GAME',
    chooseUsername: 'Choose username',
    useInstagram: '📸 Use your Instagram username!',
    contestsSoon: 'Contests and rewards coming soon 🎁',
    usernameLabel: 'Username (3-16 characters)',
    usernamePlaceholder: 'your_instagram_username',
    usernameRules: 'Letters, numbers and underscore only',
    random: 'Random',
    validateLabel: 'Validate',
    importantConfirmation: '⚠️ Important Confirmation',
    aboutToRegister: 'You are about to register the username:',
    importantNote: 'Important:',
    dontChangeUsername: 'It is strongly recommended not to change your username after validation to avoid any synchronization issues in the rankings.',
    ensureInstagram: 'Make sure it\'s your Instagram username if you want to participate in future contests!',
    modify: 'Modify',
    confirmLabel: 'Confirm',
    usernameRegistered: '✅ Username Registered',
    usernameRegisteredDesc: 'Your username has been successfully saved!',
    usernameError: 'Username must be 3-16 characters (letters, numbers, underscore)',
    usernameSaveError: 'Error saving username',
    usernameSameAsCurrent: 'This username is already yours',
    usernameChangeLimitReached: 'You have reached the username change limit (2 max)',
    usernameChangesRemaining: '{count} change(s) remaining',
    usernameNoChangesLeft: 'You can no longer change your username',
    usernameChangeWarning: 'After this confirmation, you will have {count} username change(s) left.',
    usernameFirstTimeNote: 'You can change your username a maximum of 2 times after this first registration.',
    saveError: 'Error saving username',
    submitScoreLabel: 'Submit your score',
    submitError: 'Submission error',
    serverUnavailable: 'Server unavailable, try again later',
    scoreSubmitted: 'Score submitted successfully ✅',
    classic: 'Classic',
    arcChangeant: 'Changing Arc',
    survie60s: 'Survival 30s',
    zoneMobile: 'Mobile Zone',
    sending: 'Sending...',
    submitBtn: 'Submit',
    cancel: 'Cancel',
    newLeaderboard: 'New ranking in:',
    daysShort: 'd',
    testNotification: 'Test notifications',
    testBtn: 'Test',
    testNotificationSent: 'Notification sent!',
    testNotificationSentDesc: 'Check your notifications.',
    testNotificationFailed: 'Failed',
    testNotificationFailedDesc: 'Allow notifications first.',
    luckyWheelTitle: 'Lucky Wheel',
    freeSpin: 'Free Spin!',
    watchAdToSpin: 'Watch ad to spin',
    youWon: 'You won:',
    wheelReady: 'Wheel ready!',
    wheelReadyDesc: 'Come spin the lucky wheel! 🎡',
    seasonPass: 'Season Pass',
    seasonPassShort: 'Pass',
    seasonLabel: 'Season',
    watchArrow: 'Watch →',
    dailyQuests: 'Daily Quests',
    dailyQuestsReward: '+1 💎 when both done',
    quest1Title: 'Score 20+ in one game',
    quest1Subtitle: 'Any mode',
    quest2Title: 'Use a boost in game',
    quest2Subtitle: 'Any boost or mode',
    claimDiamond: 'Claim 1 💎',
    questRewardClaimed: 'Reward claimed today!',
    questsCompleted: '{count}/2 quests completed',
    tiersToUnlock: 'Tiers to unlock',
    unlocked: 'Unlocked',
    pulsedUsername: 'YourName pulsed',
    violetUsername: 'YourName in violet',
    diamondObtained: '💎 Diamond obtained!',
    diamondObtainedDesc: 'You earned 1 diamond by completing both quests!',
    decoUnlocked: '🎉 Decoration unlocked!',
    decoUnlockedDesc: 'You unlocked "{name}"!',
    diamondBought: '💎 Diamond purchased!',
    diamondBoughtDesc: '1 coin → 1 diamond',
    diamondByAd: '💎 Diamond obtained!',
    diamondByAdDesc: 'You earned 1 diamond by watching an ad!',
    dailyBonus: 'Daily Bonus',
    slotDescription: 'Spin the machine to double your coins in one mode for 24h',
    spinInProgress: 'Spinning…',
    launchSpin: 'Spin now',
    activeUntilMidnight: 'Active until midnight',
    bonusAlreadyActive: 'Bonus already active today',
    inventoryTitle: 'Inventory',
    diamonds: 'Diamonds',
    items: 'Items',
    decorations: 'Decorations',
    leaderboardPreview: 'Leaderboard preview',
    playToApply: '⚡ Play a game to apply changes',
    removeDecoration: 'Remove decoration',
    selectDecoration: 'Select a decoration below',
    usernameColor: 'Username color',
    defaultColor: 'Default',
    violet: 'Violet',
    pulsed: 'Pulsed',
    ticketItem: 'Game Ticket',
    ticketItemDesc: 'Allows playing premium modes',
    modeTickets: 'Mode tickets',
    unlockedDecos: '{unlocked} / {total} unlocked',
    usernameTooShort: 'Username too short',
    usernameTooShortDesc: 'Minimum 3 characters.',
    usernameTooLong: 'Username too long',
    usernameTooLongDesc: 'Maximum 20 characters.',
    usernameTaken: 'Username taken',
    usernameTakenDesc: 'Choose a different username.',
    usernameUpdated: '✅ Username updated!',
    usernameUpdatedDesc: 'Your username is now "{name}".',
    classicBeginner: 'Classic Beginner',
    classicBeginnerDesc: 'Score 10 in Classic',
    classicApprentice: 'Classic Apprentice',
    classicApprenticeDesc: 'Score 15 in Classic',
    classicConfirmed: 'Classic Confirmed',
    classicConfirmedDesc: 'Score 20 in Classic',
    classicPro: 'Classic Pro',
    classicProDesc: 'Score 25 in Classic',
    arcBeginner: 'Arc Beginner',
    arcBeginnerDesc: 'Score 8 in Changing Arc',
    arcIntermediate: 'Arc Intermediate',
    arcIntermediateDesc: 'Score 12 in Changing Arc',
    arcConfirmed: 'Arc Confirmed',
    arcConfirmedDesc: 'Score 15 in Changing Arc',
    arcExpert: 'Arc Expert',
    arcExpertDesc: 'Score 20 in Changing Arc',
    survivalBeginner: 'Survival Beginner',
    survivalBeginnerDesc: 'Score 5 in Survival 30s',
    survivor: 'Survivor',
    survivorDesc: 'Score 8 in Survival 30s',
    survivalConfirmed: 'Survival Confirmed',
    survivalConfirmedDesc: 'Score 12 in Survival 30s',
    survivalMaster: 'Survival Master',
    survivalMasterDesc: 'Score 15 in Survival 30s',
    mobileNomad: 'Mobile Nomad',
    mobileNomadDesc: 'Score 8 in Mobile Zone',
    mobileHunter: 'Mobile Hunter',
    mobileHunterDesc: 'Score 12 in Mobile Zone',
    mobileConfirmed: 'Mobile Confirmed',
    mobileConfirmedDesc: 'Score 15 in Mobile Zone',
    mobileExpert: 'Mobile Expert',
    mobileExpertDesc: 'Score 20 in Mobile Zone',
    detector: 'Detector',
    detectorDesc: 'Score 5 in Trap Zone',
    minesweeper: 'Minesweeper',
    minesweeperDesc: 'Score 8 in Trap Zone',
    trapConfirmed: 'Trap Confirmed',
    trapConfirmedDesc: 'Score 10 in Trap Zone',
    trapExpert: 'Trap Expert',
    trapExpertDesc: 'Score 15 in Trap Zone',
    shortMemory: 'Short Memory',
    shortMemoryDesc: 'Score 3 in Memory Expert',
    goodMemory: 'Good Memory',
    goodMemoryDesc: 'Score 5 in Memory Expert',
    memoryConfirmed: 'Memory Confirmed',
    memoryConfirmedDesc: 'Score 8 in Memory Expert',
    eidetic: 'Eidetic Memory',
    eideticDesc: 'Score 10 in Memory Expert',
  },
  es: {
    title: 'LUCKY STOP',
    subtitle: '¡Toca en la zona verde en el momento justo!',
    bestScore: 'Mejor Puntuación',
    coins: 'Monedas',
    playNow: 'JUGAR AHORA',
    gameModes: 'MODOS DE JUEGO',
    shop: 'TIENDA',
    dailyChallenges: 'DESAFÍOS DIARIOS',
    onlineLeaderboard: 'CLASIFICACIÓN EN LÍNEA',
    theme: 'Tema',
    mode: 'Modo',
    trapWarning: '⚠️ Advertencia: una de las zonas es una trampa. Elige bien…',
    avoidTrap: '¡Evita la zona trampa!',
    trapZone: '¡Zona trampa!',
    gifts: 'Regalos',
    language: 'Idioma',
    new: 'Nuevo',
    news: 'Actualidad',
    contest: 'Concurso',
    newsAndContest: 'Actualidad y Concurso',
    comingSoon: 'Próximamente',
    comingSoonDesc: '¡Nuevas funciones próximamente! 🚀',
    inventory: 'Inventario',
    settings: 'Ajustes',
    sound: 'Sonido',
    dailyNotifications: 'Notificaciones Diarias',
    notificationDesc: 'Una notificación al día porque la clasificación te espera 🎮',
    close: 'Cerrar',
    joinUs: '¡Únete a nosotros!',
    socialDesc: '¡Sigue las novedades y participa en el próximo concurso para ganar recompensas exclusivas! 🎁',
    back: 'Volver',
    backToMenu: 'Volver al Menú',
    username: 'Nombre',
    noUsername: 'Sin nombre',
    global: 'Global',
    weekly: 'Semanal',
    refresh: 'Actualizar',
    offlineMode: 'Modo sin conexión - Reconecta para ver la clasificación',
    noScores: 'No hay puntuaciones registradas para este modo',
    beFirst: '¡Sé el primero en jugar!',
    noWeeklyScores: 'No hay puntuaciones esta semana para este modo',
    beFirstWeek: '¡Sé el primero en jugar esta semana!',
    usernameChanged: 'Nombre cambiado',
    usernameChangedDesc: 'Tu nuevo nombre se ha guardado',
    networkError: 'Error de red',
    networkErrorDesc: 'No se puede cargar la clasificación',
    shopTitle: 'TIENDA',
    shopDesc: 'Desbloquea temas, modos de juego y potenciadores',
    themes: 'Temas',
    modes: 'Modos de Juego',
    boosts: 'Potenciadores',
    equipped: 'Equipado',
    owned: 'Poseído',
    locked: 'Bloqueado',
    unlock: 'Desbloquear',
    buy: 'Comprar',
    insufficientCoins: 'Monedas insuficientes',
    insufficientCoinsDesc: 'Necesitas {amount} monedas para comprar esto.',
    themeLocked: 'Tema bloqueado',
    themeLockedDesc: '¡Completa 7 días de recompensas diarias para desbloquear este tema exclusivo!',
    packBought: '¡Pack comprado!',
    packBoughtDesc: '¡Recibiste 4 tickets para el modo Experto!',
    ticketPack: 'Pack de Tickets Experto',
    ticketPackDesc: '4 tickets para jugar al modo Memoria (Experto). 1 ticket = 1 partida.',
    freeCoinsAd: 'Ver anuncio (80 Monedas)',
    watchAdAndGet: '¡Mira un anuncio y obtén {amount} Monedas gratis!',
    adCooldown: 'Nuevo anuncio en {time}',
    boostShopEmpty: '¡Los potenciadores se obtienen a través de desafíos y recompensas diarias!',
    checkChallenges: 'Ver Desafíos',
    currentTheme: 'Tema Actual',
    equip: 'Equipar',
    lockedDays: 'Bloqueado - 7 días requeridos',
    unlock7Days: '¡Completa 7 días de recompensas diarias para desbloquear este tema legendario!',
    buyCoins: 'Comprar ({price} monedas)',
    currentTickets: 'Tickets actuales:',
    price: 'Precio:',
    buy4Tickets: 'Comprar 4 tickets ({price} monedas)',
    get5ByAd: 'Obtener 5 por anuncio',
    ticketsReceived: '¡Tickets recibidos!',
    ticketsReceivedDesc: '¡Has recibido 5 tickets! 🎫',
    modeUnlocked: 'Modo Desbloqueado',
    unlockMode: 'Desbloquear ({price} monedas)',
    earnCoinsFooter: '¡Gana monedas jugando para desbloquear nuevos temas!',
    ownedCount: 'Poseídos: {count}',
    boostBought: '¡Potenciador comprado!',
    boostBoughtDesc: 'Has comprado un potenciador {name}.',
    buyFor: 'Comprar por {price} monedas',
    getByAd: 'Obtener por anuncio',
    boostReceived: '¡Potenciador recibido!',
    boostReceivedDesc: 'Has recibido {name} {icon}',
    challengesTitle: 'DESAFÍOS DE PROGRESIÓN',
    challengeProgress: 'Progreso de desafíos',
    totalGamesPlayed: 'Total de partidas jugadas',
    claimRewards: 'Reclamar {count} potenciador(es)',
    reward: 'Recompensa',
    randomBoost: '1 potenciador aleatorio',
    score: 'Puntuación',
    level: 'Nivel',
    challengeInfo1: 'Cada modo tiene 10 niveles de progresión (10, 20, 30... hasta 100 puntos)',
    challengeInfo2: 'Alcanza niveles para ganar monedas',
    challengeInfo3: 'Desbloquea potenciadores jugando partidas (todos los modos combinados)',
    rewardClaimed: '¡Recompensa reclamada!',
    coinsReceived: '{amount} monedas añadidas a tu cuenta',
    boostsClaimed: '¡Potenciador(es) reclamado(s)!',
    boostsAdded: '{boosts} añadido(s) a tu inventario',
    challengeCompleted: '¡Nivel alcanzado! 🎉',
    challengeCompletedDesc: '{mode} - ¡Puntuación de {score} alcanzada! Reclama tu recompensa en Desafíos.',
    gamesPlayedReward: '¡{count} partidas jugadas! Reclama tu potenciador en Desafíos.',
    challenges: 'Desafíos',
    daily: 'Diarios',
    globalChallenges: 'Globales',
    dailyChallengesHeader: 'Desafíos del día',
    dailyChallengesSubtitle: '3 nuevos desafíos cada día',
    claim: 'Reclamar',
    howItWorks: '¿Cómo funciona?',
    howItWorksGames: 'Partidas jugadas (∞): cada 50 partidas → 1 potenciador.',
    howItWorksModes: 'Desafíos por modo: niveles de puntuación 10 → 100. Cada nivel alcanzado desbloquea monedas (10, 20, 30...).',
    howItWorksRewards: 'Las recompensas quedan pendientes hasta ser reclamadas.',
    games: 'partidas',
    gamesPlayed: 'Partidas jugadas',
    tier: 'Nivel',
    boostReward: '+1 potenciador',
    completed: 'Completado',
    done: '✓ Terminado',
    tierUnlocked: '¡nivel(es) desbloqueado(s)!',
    gamesPlayedTierUnlocked: '¡nivel(es) de Partidas desbloqueado(s)!',
    added: '¡añadido(s)!',
    modeSelectionTitle: 'SELECCIÓN DE MODO',
    currentMode: 'Modo actual',
    gameInProgress: 'Partida en curso',
    gameInProgressDesc: 'Termina tu partida actual para cambiar de modo.',
    selectMode: 'Elegir Este Modo',
    playNowMode: 'Jugar Ahora',
    buyInShop: 'Comprar en Tienda',
    duration: 'Duración',
    variableArc: 'Arco variable',
    mobileZone: 'Zona móvil',
    bestScoreMode: 'Mejor Puntuación',
    modeInfo: 'Las mejores puntuaciones se guardan por separado para cada modo',
    bonusAvailable: 'Bonus x2 disponible',
    bonusActive: 'x2 activo',
    bonusX2: 'Bonus x2',
    nextDrawIn: 'Próximo sorteo en',
    x2Coins: 'x2 MONEDAS',
    bestScoreLabel: 'Mejor Puntuación:',
    modeClassic: 'Clásico',
    modeArcChangeant: 'Arco Cambiante',
    modeSurvie30s: 'Supervivencia 30s',
    modeZoneMobile: 'Zona Móvil',
    modeZoneTraitresse: 'Zona Trampa',
    modeMemoireExpert: 'Memoria (Experto)',
    descClassic: 'El modo de juego original. El arco se mantiene fijo, +3% de velocidad por acierto.',
    descArcChangeant: 'Tras cada acierto, el arco verde cambia de tamaño y posición. +3% de velocidad.',
    descSurvie30s: '¡Tienes 30 segundos para conseguir el máximo de aciertos. Un fallo = game over!',
    descZoneMobile: 'El arco verde se desliza continuamente alrededor del círculo. +3% de velocidad por acierto.',
    descZoneTraitresse: '¡Varias zonas verdes, pero una es una trampa. Encuentra la zona correcta para ganar!',
    descMemoireExpert: '¡Una zona verde aparece 1 segundo, memoriza su posición y haz clic en el lugar correcto! La dificultad aumenta en cada nivel.',
    dailyRewardsTitle: 'RECOMPENSAS DIARIAS',
    yourStreak: 'Tu Racha',
    day: 'Día',
    days: 'días',
    consecutiveDays: 'días consecutivos',
    claimReward: 'Reclamar',
    comeBackTomorrow: 'Vuelve mañana',
    watchAdForCoins: 'Ver anuncio para {amount} Monedas',
    watchAdDesc: '¡Mira un anuncio y obtén {amount} Monedas gratis!',
    coinsReceivedTitle: '¡Monedas recibidas!',
    coinsReceivedDesc: '¡Recibiste {amount} monedas! 🪙',
    rewardClaimedDaily: '¡Recompensa reclamada! 🎉',
    rewardClaimedDailyDesc: 'Recibiste: {reward}',
    cooldownInfo: '¡Vuelve mañana para continuar tu racha!',
    dailyRewardsHeader: 'Recompensas Diarias',
    currentStreak: 'Racha actual:',
    dayShort: 'D',
    themeReward: 'Tema',
    boostRewardLabel: 'Potenciador',
    rewardAvailable: '¡Recompensa disponible!',
    dayLabel: 'Día {day}:',
    exclusiveTheme: '{coins} monedas + Tema Exclusivo',
    claimRewardBtn: 'Reclamar',
    rewardClaimed2: '🎉 ¡Recompensa reclamada!',
    royalTheme: '{coins} monedas + Tema Real',
    comeBackTomorrowReward: '¡Vuelve mañana para tu próxima recompensa!',
    notifBonus: 'Bonus Notificaciones',
    notifBonusAmount: '+20 monedas/día',
    notifBonusDesc: '¡Activa las notificaciones en los ajustes para recibir 20 monedas bonus cada día!',
    claimNotifBonus: 'Reclamar +20 monedas',
    notifBonusClaimed: '✓ Bonus ya reclamado hoy',
    notifBonusLocked: 'Activa las notificaciones en los ajustes para desbloquear',
    adBonus: 'Bonus Publicidad',
    adBonusAmount: '+100 monedas',
    adBonusDesc: '¡Mira un anuncio y gana 100 monedas!',
    watchAd: 'Ver un anuncio',
    notifBonusTitle: '¡Bonus Notificaciones!',
    notifBonusToast: '¡+20 monedas por activar las notificaciones! 🔔',
    customizationTitle: 'PERSONALIZACIÓN',
    apply: 'Aplicar',
    colorPalettes: '🎨 Paletas de colores',
    circles: '⭕ Círculos',
    effects: '✨ Efectos',
    combo: 'Combo',
    perfect: 'PERFECTO',
    great: 'EXCELENTE',
    good: 'BIEN',
    readyTitle: 'LUCKY STOP',
    readySubtitle: '¡Toca para comenzar!',
    tapToPlay: '¡TOCA!',
    gameOver: 'GAME OVER',
    finalScore: 'Puntuación Final',
    newRecord: '¡NUEVO RÉCORD!',
    restart: 'Jugar de Nuevo',
    mainMenu: 'Menú Principal',
    revive: 'Revivir',
    watchAdRevive: 'Ver anuncio',
    reviveSuccess: '¡Partida reanudada! 🎮',
    reviveSuccessDesc: '¡Puedes seguir jugando!',
    selectBoosts: 'Seleccionar Potenciadores',
    availableBoosts: 'Potenciadores Disponibles',
    selectedBoosts: 'Potenciadores Seleccionados',
    noBoostsAvailable: 'No hay potenciadores disponibles',
    startWithBoosts: 'Comenzar con {count} potenciador(es)',
    shield: 'Escudo',
    shieldDesc: 'Primer error perdonado',
    biggerZone: 'Zona Agrandada',
    biggerZoneDesc: 'Zona de éxito +50% más grande',
    start20: 'Inicio +20',
    start20Desc: 'Comienza con 20 puntos',
    needTicket: 'Se necesita 1 ticket para jugar a este modo',
    ticketsRemaining: '{count} ticket(s) restante(s)',
    weeklyRankings: 'Clasificaciones Semanales',
    leaderboardTitle: 'CLASIFICACIÓN MUNDIAL',
    leaderboardDesc: 'Compara tu puntuación con los mejores jugadores',
    yourRank: 'Tu Rango',
    notRanked: 'Sin clasificar',
    rank: 'Rango',
    player: 'Jugador',
    modeLabel: 'Modo',
    selectModeLeaderboard: 'Seleccionar un modo',
    selectModeDesc: 'Elige un modo para ver la clasificación',
    noScoresYet: 'Aún no hay puntuaciones',
    noScoresYetDesc: '¡Sé el primero en establecer un récord!',
    loadingScores: 'Cargando puntuaciones...',
    errorLoading: 'Error de carga',
    errorLoadingDesc: 'No se puede cargar la clasificación',
    newRankingIn: 'Nueva clasificación en',
    freeCoins: 'Monedas Gratis',
    watchAdDialogDesc: '¡Mira un anuncio corto y obtén monedas gratis!',
    coinsToWin: 'Monedas para ganar',
    adPlaying: 'Reproduciendo anuncio...',
    pleaseWait: 'Por favor espera unos segundos',
    adTip: '💡 Consejo: ¡Mira anuncios regularmente para maximizar tus ganancias!',
    coinsReceivedAd: '¡Monedas recibidas!',
    coinsReceivedAdDesc: '¡Has recibido 100 monedas! 🪙',
    menu: 'Menú',
    best: 'Mejor',
    levelLabel: 'Nivel',
    gameOverLabel: 'JUEGO TERMINADO',
    ticket: 'ticket',
    tickets: 'tickets',
    play: 'JUGAR',
    restartLabel: 'REINICIAR',
    reviveLabel: 'REVIVIR',
    noTicket: '¡Sin ticket!',
    noTicketDesc: 'Compra tickets en la tienda para jugar al modo Experto.',
    reviveUsed: 'Revivir ya usado',
    reviveUsedDesc: 'Solo puedes revivir una vez por juego.',
    reviveActivated: '¡Revivir activado!',
    reviveActivatedDesc: '¡Has sido devuelto a la vida!',
    reviveByAd: 'Revivir con anuncio',
    tapOnScreen: 'Toca la pantalla',
    tapInGreenZone: '¡Toca cuando la barra esté en la zona verde!',
    tapToStartGame: 'Toca la pantalla para empezar o presiona ESPACIO/ENTER',
    speedLabel: 'Velocidad',
    zoneLabel: 'Zona',
    buyBoostsShop: '¡Compra potenciadores en la tienda para usarlos!',
    selectBoostsNext: 'Selecciona potenciadores para tu próximo juego:',
    unavailableMode: 'No disponible para este modo',
    restartGameLabel: 'REINICIAR JUEGO',
    prepareGame: 'Prepara tu juego',
    startWithoutBoost: 'Comenzar sin potenciador',
    selectBoostsUse: 'Selecciona potenciadores para usar:',
    startGameLabel: 'COMENZAR JUEGO',
    chooseUsername: 'Elegir nombre de usuario',
    useInstagram: '📸 ¡Usa tu nombre de Instagram!',
    contestsSoon: 'Concursos y recompensas próximamente 🎁',
    usernameLabel: 'Nombre de usuario (3-16 caracteres)',
    usernamePlaceholder: 'tu_usuario_instagram',
    usernameRules: 'Solo letras, números y guión bajo',
    random: 'Aleatorio',
    validateLabel: 'Validar',
    importantConfirmation: '⚠️ Confirmación Importante',
    aboutToRegister: 'Estás a punto de registrar el nombre de usuario:',
    importantNote: 'Importante:',
    dontChangeUsername: 'Se recomienda encarecidamente no cambiar tu nombre de usuario después de la validación para evitar problemas de sincronización en las clasificaciones.',
    ensureInstagram: '¡Asegúrate de que sea tu nombre de usuario de Instagram si quieres participar en futuros concursos!',
    modify: 'Modificar',
    confirmLabel: 'Confirmar',
    usernameRegistered: '✅ Nombre Registrado',
    usernameRegisteredDesc: '¡Tu nombre de usuario se ha guardado correctamente!',
    usernameError: 'El nombre de usuario debe tener entre 3 y 16 caracteres (letras, números, guión bajo)',
    usernameSaveError: 'Error al guardar el nombre de usuario',
    usernameSameAsCurrent: 'Este nombre de usuario ya es el tuyo',
    usernameChangeLimitReached: 'Has alcanzado el límite de cambios de nombre de usuario (2 máx.)',
    usernameChangesRemaining: '{count} cambio(s) restante(s)',
    usernameNoChangesLeft: 'Ya no puedes cambiar tu nombre de usuario',
    usernameChangeWarning: 'Después de esta confirmación, te quedarán {count} cambio(s) de nombre de usuario.',
    usernameFirstTimeNote: 'Puedes cambiar tu nombre de usuario un máximo de 2 veces después de este primer registro.',
    saveError: 'Error al guardar el nombre de usuario',
    submitScoreLabel: 'Enviar tu puntuación',
    submitError: 'Error de envío',
    serverUnavailable: 'Servidor no disponible, intenta más tarde',
    scoreSubmitted: 'Puntuación enviada con éxito ✅',
    classic: 'Clásico',
    arcChangeant: 'Arco Cambiante',
    survie60s: 'Supervivencia 30s',
    zoneMobile: 'Zona Móvil',
    sending: 'Enviando...',
    submitBtn: 'Enviar',
    cancel: 'Cancelar',
    newLeaderboard: 'Nueva clasificación en:',
    daysShort: 'd',
    testNotification: 'Probar notificaciones',
    testBtn: 'Probar',
    testNotificationSent: '¡Notificación enviada!',
    testNotificationSentDesc: 'Revisa tus notificaciones.',
    testNotificationFailed: 'Falló',
    testNotificationFailedDesc: 'Permite las notificaciones primero.',
    luckyWheelTitle: 'Rueda de la Suerte',
    freeSpin: '¡Giro Gratis!',
    watchAdToSpin: 'Ver anuncio para girar',
    youWon: 'Ganaste:',
    wheelReady: '¡Rueda lista!',
    wheelReadyDesc: '¡Ven a girar la rueda de la suerte! 🎡',
    seasonPass: 'Pase de Temporada',
    seasonPassShort: 'Pase',
    seasonLabel: 'Temporada',
    watchArrow: 'Ver →',
    dailyQuests: 'Misiones del día',
    dailyQuestsReward: '+1 💎 al completar ambas',
    quest1Title: 'Puntuación 20+ en una partida',
    quest1Subtitle: 'Cualquier modo',
    quest2Title: 'Usar un potenciador en juego',
    quest2Subtitle: 'Cualquier potenciador o modo',
    claimDiamond: 'Reclamar 1 💎',
    questRewardClaimed: '¡Recompensa reclamada hoy!',
    questsCompleted: '{count}/2 misiones completadas',
    tiersToUnlock: 'Niveles por desbloquear',
    unlocked: 'Desbloqueado',
    pulsedUsername: 'TuNombre pulsado',
    violetUsername: 'TuNombre en violeta',
    diamondObtained: '💎 ¡Diamante obtenido!',
    diamondObtainedDesc: '¡Has ganado 1 diamante al completar las 2 misiones!',
    decoUnlocked: '🎉 ¡Decoración desbloqueada!',
    decoUnlockedDesc: '¡Has desbloqueado "{name}"!',
    diamondBought: '💎 ¡Diamante comprado!',
    diamondBoughtDesc: '1 moneda → 1 diamante',
    diamondByAd: '💎 ¡Diamante obtenido!',
    diamondByAdDesc: '¡Has ganado 1 diamante viendo un anuncio!',
    dailyBonus: 'Bonus Diario',
    slotDescription: 'Gira la máquina para duplicar tus monedas en un modo durante 24h',
    spinInProgress: 'Girando…',
    launchSpin: 'Girar ahora',
    activeUntilMidnight: 'Activo hasta medianoche',
    bonusAlreadyActive: 'Bonus ya activado hoy',
    inventoryTitle: 'Inventario',
    diamonds: 'Diamantes',
    items: 'Objetos',
    decorations: 'Decoraciones',
    leaderboardPreview: 'Vista previa del ranking',
    playToApply: '⚡ Juega una partida para aplicar los cambios',
    removeDecoration: 'Quitar decoración',
    selectDecoration: 'Selecciona una decoración abajo',
    usernameColor: 'Color del nombre',
    defaultColor: 'Predeterminado',
    violet: 'Violeta',
    pulsed: 'Pulsado',
    ticketItem: 'Ticket de Partida',
    ticketItemDesc: 'Permite jugar en modos premium',
    modeTickets: 'Tickets de modo',
    unlockedDecos: '{unlocked} / {total} desbloqueada(s)',
    usernameTooShort: 'Nombre muy corto',
    usernameTooShortDesc: 'Mínimo 3 caracteres.',
    usernameTooLong: 'Nombre muy largo',
    usernameTooLongDesc: 'Máximo 20 caracteres.',
    usernameTaken: 'Nombre ya tomado',
    usernameTakenDesc: 'Elige otro nombre.',
    usernameUpdated: '✅ ¡Nombre actualizado!',
    usernameUpdatedDesc: 'Tu nombre ahora es "{name}".',
    classicBeginner: 'Clásico Principiante',
    classicBeginnerDesc: 'Consigue 10 en Clásico',
    classicApprentice: 'Clásico Aprendiz',
    classicApprenticeDesc: 'Consigue 15 en Clásico',
    classicConfirmed: 'Clásico Confirmado',
    classicConfirmedDesc: 'Consigue 20 en Clásico',
    classicPro: 'Clásico Pro',
    classicProDesc: 'Consigue 25 en Clásico',
    arcBeginner: 'Arco Principiante',
    arcBeginnerDesc: 'Consigue 8 en Arco Cambiante',
    arcIntermediate: 'Arco Intermedio',
    arcIntermediateDesc: 'Consigue 12 en Arco Cambiante',
    arcConfirmed: 'Arco Confirmado',
    arcConfirmedDesc: 'Consigue 15 en Arco Cambiante',
    arcExpert: 'Arco Experto',
    arcExpertDesc: 'Consigue 20 en Arco Cambiante',
    survivalBeginner: 'Superviviente Principiante',
    survivalBeginnerDesc: 'Consigue 5 en Supervivencia 30s',
    survivor: 'Superviviente',
    survivorDesc: 'Consigue 8 en Supervivencia 30s',
    survivalConfirmed: 'Supervivencia Confirmado',
    survivalConfirmedDesc: 'Consigue 12 en Supervivencia 30s',
    survivalMaster: 'Maestro Supervivencia',
    survivalMasterDesc: 'Consigue 15 en Supervivencia 30s',
    mobileNomad: 'Zona Nómada',
    mobileNomadDesc: 'Consigue 8 en Zona Móvil',
    mobileHunter: 'Cazador Móvil',
    mobileHunterDesc: 'Consigue 12 en Zona Móvil',
    mobileConfirmed: 'Móvil Confirmado',
    mobileConfirmedDesc: 'Consigue 15 en Zona Móvil',
    mobileExpert: 'Experto Móvil',
    mobileExpertDesc: 'Consigue 20 en Zona Móvil',
    detector: 'Detector',
    detectorDesc: 'Consigue 5 en Zona Trampa',
    minesweeper: 'Desminador',
    minesweeperDesc: 'Consigue 8 en Zona Trampa',
    trapConfirmed: 'Trampa Confirmado',
    trapConfirmedDesc: 'Consigue 10 en Zona Trampa',
    trapExpert: 'Experto Desminador',
    trapExpertDesc: 'Consigue 15 en Zona Trampa',
    shortMemory: 'Memoria corta',
    shortMemoryDesc: 'Consigue 3 en Memoria Experto',
    goodMemory: 'Buena memoria',
    goodMemoryDesc: 'Consigue 5 en Memoria Experto',
    memoryConfirmed: 'Memoria Confirmado',
    memoryConfirmedDesc: 'Consigue 8 en Memoria Experto',
    eidetic: 'Memoria eidética',
    eideticDesc: 'Consigue 10 en Memoria Experto',
  },
};
