import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'fr' | 'en' | 'es' | 'de' | 'it' | 'pt' | 'ar' | 'ja' | 'zh';

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
}

export const useLanguage = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'fr',
      setLanguage: (language) => set({ language }),
    }),
    {
      name: 'lucky-stop-language',
    }
  )
);

export const translations = {
  fr: {
    // Main Menu
    title: 'LUCKY STOP',
    subtitle: 'Tapez dans la zone verte au bon moment!',
    bestScore: 'Meilleur Score',
    coins: 'Coins',
    playNow: 'JOUER MAINTENANT',
    gameModes: 'MODES DE JEU',
    shop: 'BOUTIQUE',
    dailyChallenges: 'DÉFIS QUOTIDIENS',
    onlineLeaderboard: 'CLASSEMENT EN LIGNE',
    theme: 'Thème',
    mode: 'Mode',
    trapWarning: '⚠️ Attention : une des zones est un piège. Choisis bien…',
    avoidTrap: 'Évite la zone piégée !',
    trapZone: 'Zone traîtresse !',
    gifts: 'Cadeaux',
    language: 'Langue',
    new: 'Nouveau',
    comingSoon: 'Coming Soon',
    comingSoonDesc: 'De nouvelles fonctionnalités arrivent bientôt ! 🚀',
    // Settings
    settings: 'Réglages',
    sound: 'Son',
    dailyNotifications: 'Notifications quotidiennes',
    notificationDesc: 'Une notification par jour car le classement n\'attend que toi 🎮',
    close: 'Fermer',
    // Social
    joinUs: 'Rejoins-nous !',
    socialDesc: 'Suis l\'actualité et participe au prochain concours pour gagner des récompenses exclusives ! 🎁',
    // Leaderboard
    back: 'Retour',
    backToMenu: 'Retour au Menu',
    username: 'Pseudo',
    noUsername: 'Aucun pseudo',
    global: 'Global',
    weekly: 'Hebdomadaire',
    refresh: 'Actualiser',
    offlineMode: 'Mode hors ligne - Reconnectez-vous pour voir le classement',
    noScores: 'Aucun score enregistré pour ce mode',
    beFirst: 'Sois le premier à jouer !',
    noWeeklyScores: 'Aucun score cette semaine pour ce mode',
    beFirstWeek: 'Sois le premier à jouer cette semaine !',
    usernameChanged: 'Pseudo modifié',
    usernameChangedDesc: 'Votre nouveau pseudo a été sauvegardé',
    networkError: 'Erreur réseau',
    networkErrorDesc: 'Impossible de charger le classement',
    // Shop
    shopTitle: 'BOUTIQUE',
    shopDesc: 'Débloquez des thèmes, modes de jeux et boosts',
    themes: 'Thèmes',
    modes: 'Modes de jeux',
    boosts: 'Boosts',
    equipped: 'Équipé',
    owned: 'Possédé',
    locked: 'Verrouillé',
    unlock: 'Débloquer',
    buy: 'Acheter',
    insufficientCoins: 'Coins insuffisants',
    insufficientCoinsDesc: 'Il te faut {amount} coins pour acheter ceci.',
    themeLocked: 'Thème verrouillé',
    themeLockedDesc: 'Complétez 7 jours de récompenses quotidiennes pour débloquer ce thème exclusif !',
    packBought: 'Pack acheté !',
    packBoughtDesc: 'Tu as reçu 4 tickets pour le mode Expert !',
    ticketPack: 'Pack de Tickets Expert',
    ticketPackDesc: '4 tickets pour jouer au mode Mémoire (Expert). 1 ticket = 1 partie.',
    freeCoinsAd: 'Regarder une pub (80 Coins)',
    watchAdAndGet: 'Regarde une pub et obtiens {amount} Coins gratuitement !',
    adCooldown: 'Nouvelle pub dans {time}',
    boostShopEmpty: 'Les boosts s\'obtiennent via les défis et récompenses quotidiennes !',
    checkChallenges: 'Voir les Défis',
    // Challenges
    challengesTitle: 'DÉFIS DE PROGRESSION',
    challengeProgress: 'Progression des défis',
    totalGamesPlayed: 'Total de parties jouées',
    claimRewards: 'Réclamer {count} boost(s)',
    reward: 'Récompense',
    randomBoost: '1 boost aléatoire',
    score: 'Score',
    level: 'Niveau',
    challengeInfo1: 'Chaque mode a 10 paliers de progression (10, 20, 30... jusqu\'à 100 points)',
    challengeInfo2: 'Atteignez les paliers pour gagner des coins',
    challengeInfo3: 'Débloquez des boosts en jouant des parties (tous modes confondus)',
    rewardClaimed: 'Récompense réclamée !',
    coinsReceived: '{amount} coins ajoutés à votre compte',
    boostsClaimed: 'Boost(s) réclamé(s) !',
    boostsAdded: '{boosts} ajouté(s) à votre inventaire',
    challengeCompleted: 'Palier atteint ! 🎉',
    challengeCompletedDesc: '{mode} - Score de {score} atteint ! Réclamez votre récompense dans les Défis.',
    gamesPlayedReward: '{count} parties jouées ! Réclamez votre boost dans les Défis.',
    // Modes
    modeSelectionTitle: 'SÉLECTION DU MODE',
    currentMode: 'Mode actuel',
    gameInProgress: 'Partie en cours',
    gameInProgressDesc: 'Termine ta partie actuelle pour changer de mode.',
    selectMode: 'Choisir ce Mode',
    playNowMode: 'Jouer maintenant',
    buyInShop: 'Acheter en Boutique',
    duration: 'Durée',
    variableArc: 'Arc variable',
    mobileZone: 'Zone mobile',
    bestScoreMode: 'Meilleur Score',
    modeInfo: 'Les meilleurs scores sont sauvegardés séparément pour chaque mode',
    // Daily Rewards
    dailyRewardsTitle: 'RÉCOMPENSES QUOTIDIENNES',
    yourStreak: 'Ta Série',
    day: 'Jour',
    days: 'jours',
    consecutiveDays: 'jours consécutifs',
    claimReward: 'Récupérer',
    comeBackTomorrow: 'Reviens demain',
    watchAdForCoins: 'Regarder une pub pour {amount} Coins',
    watchAdDesc: 'Regarde une pub et obtiens {amount} Coins gratuitement !',
    coinsReceivedTitle: 'Coins reçus !',
    coinsReceivedDesc: 'Tu as reçu {amount} coins ! 🪙',
    rewardClaimedDaily: 'Récompense réclamée ! 🎉',
    rewardClaimedDailyDesc: 'Tu as reçu : {reward}',
    cooldownInfo: 'Reviens demain pour continuer ta série !',
    // Customization
    customizationTitle: 'PERSONNALISATION',
    apply: 'Appliquer',
    colorPalettes: '🎨 Palettes de couleurs',
    circles: '⭕ Cercles',
    effects: '✨ Effets',
    // Game
    combo: 'Combo',
    perfect: 'PARFAIT',
    great: 'EXCELLENT',
    good: 'BIEN',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'Appuie pour commencer !',
    tapToPlay: 'TAPE !',
    gameOver: 'GAME OVER',
    finalScore: 'Score final',
    newRecord: 'NOUVEAU RECORD !',
    restart: 'Rejouer',
    mainMenu: 'Menu Principal',
    revive: 'Revivre',
    watchAdRevive: 'Regarder une pub',
    reviveSuccess: 'Partie relancée ! 🎮',
    reviveSuccessDesc: 'Tu peux continuer à jouer !',
    selectBoosts: 'Sélectionner des Boosts',
    availableBoosts: 'Boosts Disponibles',
    selectedBoosts: 'Boosts Sélectionnés',
    noBoostsAvailable: 'Aucun boost disponible',
    startWithBoosts: 'Commencer avec {count} boost(s)',
    shield: 'Bouclier',
    shieldDesc: 'Première erreur pardonnée',
    biggerZone: 'Zone agrandie',
    biggerZoneDesc: 'Zone de succès +50% plus grande',
    start20: 'Départ +20',
    start20Desc: 'Commence avec 20 points',
    needTicket: 'Il faut 1 ticket pour jouer à ce mode',
    ticketsRemaining: '{count} ticket(s) restant(s)',
  },
  en: {
    // Main Menu
    title: 'LUCKY STOP',
    subtitle: 'Tap in the green zone at the right time!',
    bestScore: 'Best Score',
    coins: 'Coins',
    playNow: 'PLAY NOW',
    gameModes: 'GAME MODES',
    shop: 'SHOP',
    dailyChallenges: 'DAILY CHALLENGES',
    onlineLeaderboard: 'ONLINE LEADERBOARD',
    theme: 'Theme',
    mode: 'Mode',
    trapWarning: '⚠️ Warning: one of the zones is a trap. Choose wisely…',
    avoidTrap: 'Avoid the trap zone!',
    trapZone: 'Trap zone!',
    gifts: 'Gifts',
    language: 'Language',
    new: 'New',
    comingSoon: 'Coming Soon',
    comingSoonDesc: 'New features coming soon! 🚀',
    // Settings
    settings: 'Settings',
    sound: 'Sound',
    dailyNotifications: 'Daily Notifications',
    notificationDesc: 'One notification per day because the leaderboard is waiting for you 🎮',
    close: 'Close',
    // Social
    joinUs: 'Join Us!',
    socialDesc: 'Follow the news and participate in the next contest to win exclusive rewards! 🎁',
    // Leaderboard
    back: 'Back',
    backToMenu: 'Back to Menu',
    username: 'Username',
    noUsername: 'No username',
    global: 'Global',
    weekly: 'Weekly',
    refresh: 'Refresh',
    offlineMode: 'Offline mode - Reconnect to see the leaderboard',
    noScores: 'No scores recorded for this mode',
    beFirst: 'Be the first to play!',
    noWeeklyScores: 'No scores this week for this mode',
    beFirstWeek: 'Be the first to play this week!',
    usernameChanged: 'Username changed',
    usernameChangedDesc: 'Your new username has been saved',
    networkError: 'Network error',
    networkErrorDesc: 'Unable to load leaderboard',
    // Shop
    shopTitle: 'SHOP',
    shopDesc: 'Unlock themes, game modes and boosts',
    themes: 'Themes',
    modes: 'Game Modes',
    boosts: 'Boosts',
    equipped: 'Equipped',
    owned: 'Owned',
    locked: 'Locked',
    unlock: 'Unlock',
    buy: 'Buy',
    insufficientCoins: 'Insufficient Coins',
    insufficientCoinsDesc: 'You need {amount} coins to buy this.',
    themeLocked: 'Theme Locked',
    themeLockedDesc: 'Complete 7 days of daily rewards to unlock this exclusive theme!',
    packBought: 'Pack Purchased!',
    packBoughtDesc: 'You received 4 tickets for Expert mode!',
    ticketPack: 'Expert Tickets Pack',
    ticketPackDesc: '4 tickets to play Memory (Expert) mode. 1 ticket = 1 game.',
    freeCoinsAd: 'Watch Ad (80 Coins)',
    watchAdAndGet: 'Watch an ad and get {amount} Coins for free!',
    adCooldown: 'New ad in {time}',
    boostShopEmpty: 'Boosts are obtained through challenges and daily rewards!',
    checkChallenges: 'View Challenges',
    // Challenges
    challengesTitle: 'PROGRESSION CHALLENGES',
    challengeProgress: 'Challenge progress',
    totalGamesPlayed: 'Total games played',
    claimRewards: 'Claim {count} boost(s)',
    reward: 'Reward',
    randomBoost: '1 random boost',
    score: 'Score',
    level: 'Level',
    challengeInfo1: 'Each mode has 10 progression tiers (10, 20, 30... up to 100 points)',
    challengeInfo2: 'Reach tiers to earn coins',
    challengeInfo3: 'Unlock boosts by playing games (all modes combined)',
    rewardClaimed: 'Reward Claimed!',
    coinsReceived: '{amount} coins added to your account',
    boostsClaimed: 'Boost(s) Claimed!',
    boostsAdded: '{boosts} added to your inventory',
    challengeCompleted: 'Tier Reached! 🎉',
    challengeCompletedDesc: '{mode} - Score of {score} reached! Claim your reward in Challenges.',
    gamesPlayedReward: '{count} games played! Claim your boost in Challenges.',
    // Modes
    modeSelectionTitle: 'MODE SELECTION',
    currentMode: 'Current Mode',
    gameInProgress: 'Game in Progress',
    gameInProgressDesc: 'Finish your current game to change mode.',
    selectMode: 'Choose This Mode',
    playNowMode: 'Play Now',
    buyInShop: 'Buy in Shop',
    duration: 'Duration',
    variableArc: 'Variable arc',
    mobileZone: 'Mobile zone',
    bestScoreMode: 'Best Score',
    modeInfo: 'Best scores are saved separately for each mode',
    // Daily Rewards
    dailyRewardsTitle: 'DAILY REWARDS',
    yourStreak: 'Your Streak',
    day: 'Day',
    days: 'days',
    consecutiveDays: 'consecutive days',
    claimReward: 'Claim',
    comeBackTomorrow: 'Come back tomorrow',
    watchAdForCoins: 'Watch Ad for {amount} Coins',
    watchAdDesc: 'Watch an ad and get {amount} Coins for free!',
    coinsReceivedTitle: 'Coins Received!',
    coinsReceivedDesc: 'You received {amount} coins! 🪙',
    rewardClaimedDaily: 'Reward Claimed! 🎉',
    rewardClaimedDailyDesc: 'You received: {reward}',
    cooldownInfo: 'Come back tomorrow to continue your streak!',
    // Customization
    customizationTitle: 'CUSTOMIZATION',
    apply: 'Apply',
    colorPalettes: '🎨 Color Palettes',
    circles: '⭕ Circles',
    effects: '✨ Effects',
    // Game
    combo: 'Combo',
    perfect: 'PERFECT',
    great: 'GREAT',
    good: 'GOOD',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'Tap to start!',
    tapToPlay: 'TAP!',
    gameOver: 'GAME OVER',
    finalScore: 'Final Score',
    newRecord: 'NEW RECORD!',
    restart: 'Play Again',
    mainMenu: 'Main Menu',
    revive: 'Revive',
    watchAdRevive: 'Watch Ad',
    reviveSuccess: 'Game Revived! 🎮',
    reviveSuccessDesc: 'You can continue playing!',
    selectBoosts: 'Select Boosts',
    availableBoosts: 'Available Boosts',
    selectedBoosts: 'Selected Boosts',
    noBoostsAvailable: 'No boosts available',
    startWithBoosts: 'Start with {count} boost(s)',
    shield: 'Shield',
    shieldDesc: 'First mistake forgiven',
    biggerZone: 'Bigger Zone',
    biggerZoneDesc: 'Success zone +50% larger',
    start20: 'Start +20',
    start20Desc: 'Start with 20 points',
    needTicket: 'Need 1 ticket to play this mode',
    ticketsRemaining: '{count} ticket(s) remaining',
  },
  es: {
    // Main Menu (même structure que FR/EN)
    title: 'LUCKY STOP',
    subtitle: '¡Toca en la zona verde en el momento justo!',
    bestScore: 'Mejor Puntuación',
    coins: 'Monedas',
    playNow: 'JUGAR AHORA',
    gameModes: 'MODOS DE JUEGO',
    shop: 'TIENDA',
    dailyChallenges: 'DESAFÍOS DIARIOS',
    onlineLeaderboard: 'CLASIFICACIÓN EN LÍNEA',
    theme: 'Tema',
    mode: 'Modo',
    trapWarning: '⚠️ Advertencia: una de las zonas es una trampa. Elige bien…',
    avoidTrap: '¡Evita la zona trampa!',
    trapZone: '¡Zona trampa!',
    gifts: 'Regalos',
    language: 'Idioma',
    new: 'Nuevo',
    comingSoon: 'Próximamente',
    comingSoonDesc: '¡Nuevas funciones próximamente! 🚀',
    settings: 'Ajustes',
    sound: 'Sonido',
    dailyNotifications: 'Notificaciones Diarias',
    notificationDesc: 'Una notificación al día porque la clasificación te espera 🎮',
    close: 'Cerrar',
    joinUs: '¡Únete a nosotros!',
    socialDesc: '¡Sigue las novedades y participa en el próximo concurso para ganar recompensas exclusivas! 🎁',
    back: 'Volver',
    backToMenu: 'Volver al Menú',
    username: 'Nombre',
    noUsername: 'Sin nombre',
    global: 'Global',
    weekly: 'Semanal',
    refresh: 'Actualizar',
    offlineMode: 'Modo sin conexión - Reconecta para ver la clasificación',
    noScores: 'No hay puntuaciones registradas para este modo',
    beFirst: '¡Sé el primero en jugar!',
    noWeeklyScores: 'No hay puntuaciones esta semana para este modo',
    beFirstWeek: '¡Sé el primero en jugar esta semana!',
    usernameChanged: 'Nombre cambiado',
    usernameChangedDesc: 'Tu nuevo nombre se ha guardado',
    networkError: 'Error de red',
    networkErrorDesc: 'No se puede cargar la clasificación',
    shopTitle: 'TIENDA',
    shopDesc: 'Desbloquea temas, modos de juego y potenciadores',
    themes: 'Temas',
    modes: 'Modos de Juego',
    boosts: 'Potenciadores',
    equipped: 'Equipado',
    owned: 'Poseído',
    locked: 'Bloqueado',
    unlock: 'Desbloquear',
    buy: 'Comprar',
    insufficientCoins: 'Monedas insuficientes',
    insufficientCoinsDesc: 'Necesitas {amount} monedas para comprar esto.',
    themeLocked: 'Tema bloqueado',
    themeLockedDesc: '¡Completa 7 días de recompensas diarias para desbloquear este tema exclusivo!',
    packBought: '¡Pack comprado!',
    packBoughtDesc: '¡Recibiste 4 tickets para el modo Experto!',
    ticketPack: 'Pack de Tickets Experto',
    ticketPackDesc: '4 tickets para jugar al modo Memoria (Experto). 1 ticket = 1 partida.',
    freeCoinsAd: 'Ver anuncio (80 Monedas)',
    watchAdAndGet: '¡Mira un anuncio y obtén {amount} Monedas gratis!',
    adCooldown: 'Nuevo anuncio en {time}',
    boostShopEmpty: '¡Los potenciadores se obtienen a través de desafíos y recompensas diarias!',
    checkChallenges: 'Ver Desafíos',
    challengesTitle: 'DESAFÍOS DE PROGRESIÓN',
    challengeProgress: 'Progreso de desafíos',
    totalGamesPlayed: 'Total de partidas jugadas',
    claimRewards: 'Reclamar {count} potenciador(es)',
    reward: 'Recompensa',
    randomBoost: '1 potenciador aleatorio',
    score: 'Puntuación',
    level: 'Nivel',
    challengeInfo1: 'Cada modo tiene 10 niveles de progresión (10, 20, 30... hasta 100 puntos)',
    challengeInfo2: 'Alcanza niveles para ganar monedas',
    challengeInfo3: 'Desbloquea potenciadores jugando partidas (todos los modos combinados)',
    rewardClaimed: '¡Recompensa reclamada!',
    coinsReceived: '{amount} monedas añadidas a tu cuenta',
    boostsClaimed: '¡Potenciador(es) reclamado(s)!',
    boostsAdded: '{boosts} añadido(s) a tu inventario',
    challengeCompleted: '¡Nivel alcanzado! 🎉',
    challengeCompletedDesc: '{mode} - ¡Puntuación de {score} alcanzada! Reclama tu recompensa en Desafíos.',
    gamesPlayedReward: '¡{count} partidas jugadas! Reclama tu potenciador en Desafíos.',
    modeSelectionTitle: 'SELECCIÓN DE MODO',
    currentMode: 'Modo actual',
    gameInProgress: 'Partida en curso',
    gameInProgressDesc: 'Termina tu partida actual para cambiar de modo.',
    selectMode: 'Elegir Este Modo',
    playNowMode: 'Jugar Ahora',
    buyInShop: 'Comprar en Tienda',
    duration: 'Duración',
    variableArc: 'Arco variable',
    mobileZone: 'Zona móvil',
    bestScoreMode: 'Mejor Puntuación',
    modeInfo: 'Las mejores puntuaciones se guardan por separado para cada modo',
    dailyRewardsTitle: 'RECOMPENSAS DIARIAS',
    yourStreak: 'Tu Racha',
    day: 'Día',
    days: 'días',
    consecutiveDays: 'días consecutivos',
    claimReward: 'Reclamar',
    comeBackTomorrow: 'Vuelve mañana',
    watchAdForCoins: 'Ver anuncio para {amount} Monedas',
    watchAdDesc: '¡Mira un anuncio y obtén {amount} Monedas gratis!',
    coinsReceivedTitle: '¡Monedas recibidas!',
    coinsReceivedDesc: '¡Recibiste {amount} monedas! 🪙',
    rewardClaimedDaily: '¡Recompensa reclamada! 🎉',
    rewardClaimedDailyDesc: 'Recibiste: {reward}',
    cooldownInfo: '¡Vuelve mañana para continuar tu racha!',
    customizationTitle: 'PERSONALIZACIÓN',
    apply: 'Aplicar',
    colorPalettes: '🎨 Paletas de colores',
    circles: '⭕ Círculos',
    effects: '✨ Efectos',
    combo: 'Combo',
    perfect: 'PERFECTO',
    great: 'EXCELENTE',
    good: 'BIEN',
    readyTitle: 'LUCKY STOP',
    readySubtitle: '¡Toca para comenzar!',
    tapToPlay: '¡TOCA!',
    gameOver: 'GAME OVER',
    finalScore: 'Puntuación Final',
    newRecord: '¡NUEVO RÉCORD!',
    restart: 'Jugar de Nuevo',
    mainMenu: 'Menú Principal',
    revive: 'Revivir',
    watchAdRevive: 'Ver anuncio',
    reviveSuccess: '¡Partida reanudada! 🎮',
    reviveSuccessDesc: '¡Puedes seguir jugando!',
    selectBoosts: 'Seleccionar Potenciadores',
    availableBoosts: 'Potenciadores Disponibles',
    selectedBoosts: 'Potenciadores Seleccionados',
    noBoostsAvailable: 'No hay potenciadores disponibles',
    startWithBoosts: 'Comenzar con {count} potenciador(es)',
    shield: 'Escudo',
    shieldDesc: 'Primer error perdonado',
    biggerZone: 'Zona Agrandada',
    biggerZoneDesc: 'Zona de éxito +50% más grande',
    start20: 'Inicio +20',
    start20Desc: 'Comienza con 20 puntos',
    needTicket: 'Se necesita 1 ticket para jugar a este modo',
    ticketsRemaining: '{count} ticket(s) restante(s)',
  },
  de: {
    title: 'LUCKY STOP',
    subtitle: 'Tippe zur richtigen Zeit in die grüne Zone!',
    bestScore: 'Bester Score',
    coins: 'Münzen',
    playNow: 'JETZT SPIELEN',
    gameModes: 'SPIELMODI',
    shop: 'SHOP',
    dailyChallenges: 'TÄGLICHE HERAUSFORDERUNGEN',
    onlineLeaderboard: 'ONLINE-RANGLISTE',
    theme: 'Thema',
    mode: 'Modus',
    trapWarning: '⚠️ Warnung: Eine der Zonen ist eine Falle. Wähle weise…',
    avoidTrap: 'Vermeide die Fallenzone!',
    trapZone: 'Fallenzone!',
    gifts: 'Geschenke',
    language: 'Sprache',
    new: 'Neu',
    comingSoon: 'Demnächst',
    comingSoonDesc: 'Neue Funktionen kommen bald! 🚀',
    settings: 'Einstellungen',
    sound: 'Ton',
    dailyNotifications: 'Tägliche Benachrichtigungen',
    notificationDesc: 'Eine Benachrichtigung pro Tag, weil die Rangliste auf dich wartet 🎮',
    close: 'Schließen',
    joinUs: 'Tritt uns bei!',
    socialDesc: 'Folge den News und nimm am nächsten Wettbewerb teil, um exklusive Belohnungen zu gewinnen! 🎁',
    back: 'Zurück',
    backToMenu: 'Zurück zum Menü',
    username: 'Benutzername',
    noUsername: 'Kein Benutzername',
    global: 'Global',
    weekly: 'Wöchentlich',
    refresh: 'Aktualisieren',
    offlineMode: 'Offline-Modus - Verbinden Sie sich erneut, um die Rangliste zu sehen',
    noScores: 'Keine Punkte für diesen Modus aufgezeichnet',
    beFirst: 'Sei der Erste, der spielt!',
    noWeeklyScores: 'Diese Woche keine Punkte für diesen Modus',
    beFirstWeek: 'Sei der Erste, der diese Woche spielt!',
    usernameChanged: 'Benutzername geändert',
    usernameChangedDesc: 'Ihr neuer Benutzername wurde gespeichert',
    networkError: 'Netzwerkfehler',
    networkErrorDesc: 'Rangliste kann nicht geladen werden',
    shopTitle: 'SHOP',
    shopDesc: 'Themen, Spielmodi und Boosts freischalten',
    themes: 'Themen',
    modes: 'Spielmodi',
    boosts: 'Boosts',
    equipped: 'Ausgerüstet',
    owned: 'Besessen',
    locked: 'Gesperrt',
    unlock: 'Freischalten',
    buy: 'Kaufen',
    insufficientCoins: 'Nicht genug Münzen',
    insufficientCoinsDesc: 'Du brauchst {amount} Münzen, um dies zu kaufen.',
    themeLocked: 'Thema gesperrt',
    themeLockedDesc: 'Vervollständige 7 Tage tägliche Belohnungen, um dieses exklusive Thema freizuschalten!',
    packBought: 'Pack gekauft!',
    packBoughtDesc: 'Du hast 4 Tickets für den Experten-Modus erhalten!',
    ticketPack: 'Experten-Tickets Pack',
    ticketPackDesc: '4 Tickets zum Spielen des Gedächtnis (Experte) Modus. 1 Ticket = 1 Spiel.',
    freeCoinsAd: 'Werbung ansehen (80 Münzen)',
    watchAdAndGet: 'Schau dir eine Werbung an und erhalte {amount} Münzen kostenlos!',
    adCooldown: 'Neue Werbung in {time}',
    boostShopEmpty: 'Boosts werden durch Herausforderungen und tägliche Belohnungen erhalten!',
    checkChallenges: 'Herausforderungen ansehen',
    challengesTitle: 'FORTSCHRITTS-HERAUSFORDERUNGEN',
    challengeProgress: 'Herausforderungsfortschritt',
    totalGamesPlayed: 'Gespielte Spiele insgesamt',
    claimRewards: '{count} Boost(s) beanspruchen',
    reward: 'Belohnung',
    randomBoost: '1 zufälliger Boost',
    score: 'Punktzahl',
    level: 'Level',
    challengeInfo1: 'Jeder Modus hat 10 Fortschrittsstufen (10, 20, 30... bis 100 Punkte)',
    challengeInfo2: 'Erreiche Stufen, um Münzen zu verdienen',
    challengeInfo3: 'Schalte Boosts frei, indem du Spiele spielst (alle Modi kombiniert)',
    rewardClaimed: 'Belohnung beansprucht!',
    coinsReceived: '{amount} Münzen zu deinem Konto hinzugefügt',
    boostsClaimed: 'Boost(s) beansprucht!',
    boostsAdded: '{boosts} zu deinem Inventar hinzugefügt',
    challengeCompleted: 'Stufe erreicht! 🎉',
    challengeCompletedDesc: '{mode} - Punktzahl von {score} erreicht! Fordere deine Belohnung in den Herausforderungen an.',
    gamesPlayedReward: '{count} Spiele gespielt! Fordere deinen Boost in den Herausforderungen an.',
    modeSelectionTitle: 'MODUS-AUSWAHL',
    currentMode: 'Aktueller Modus',
    gameInProgress: 'Spiel läuft',
    gameInProgressDesc: 'Beende dein aktuelles Spiel, um den Modus zu wechseln.',
    selectMode: 'Diesen Modus wählen',
    playNowMode: 'Jetzt spielen',
    buyInShop: 'Im Shop kaufen',
    duration: 'Dauer',
    variableArc: 'Variabler Bogen',
    mobileZone: 'Mobile Zone',
    bestScoreMode: 'Bester Score',
    modeInfo: 'Die besten Punktzahlen werden für jeden Modus separat gespeichert',
    dailyRewardsTitle: 'TÄGLICHE BELOHNUNGEN',
    yourStreak: 'Deine Serie',
    day: 'Tag',
    days: 'Tage',
    consecutiveDays: 'aufeinanderfolgende Tage',
    claimReward: 'Beanspruchen',
    comeBackTomorrow: 'Komm morgen zurück',
    watchAdForCoins: 'Werbung für {amount} Münzen ansehen',
    watchAdDesc: 'Schau dir eine Werbung an und erhalte {amount} Münzen kostenlos!',
    coinsReceivedTitle: 'Münzen erhalten!',
    coinsReceivedDesc: 'Du hast {amount} Münzen erhalten! 🪙',
    rewardClaimedDaily: 'Belohnung beansprucht! 🎉',
    rewardClaimedDailyDesc: 'Du hast erhalten: {reward}',
    cooldownInfo: 'Komm morgen zurück, um deine Serie fortzusetzen!',
    customizationTitle: 'ANPASSUNG',
    apply: 'Anwenden',
    colorPalettes: '🎨 Farbpaletten',
    circles: '⭕ Kreise',
    effects: '✨ Effekte',
    combo: 'Combo',
    perfect: 'PERFEKT',
    great: 'GROSSARTIG',
    good: 'GUT',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'Tippe zum Starten!',
    tapToPlay: 'TIPPEN!',
    gameOver: 'GAME OVER',
    finalScore: 'Endpunktzahl',
    newRecord: 'NEUER REKORD!',
    restart: 'Nochmal spielen',
    mainMenu: 'Hauptmenü',
    revive: 'Wiederbeleben',
    watchAdRevive: 'Werbung ansehen',
    reviveSuccess: 'Spiel wiederbelebt! 🎮',
    reviveSuccessDesc: 'Du kannst weiterspielen!',
    selectBoosts: 'Boosts auswählen',
    availableBoosts: 'Verfügbare Boosts',
    selectedBoosts: 'Ausgewählte Boosts',
    noBoostsAvailable: 'Keine Boosts verfügbar',
    startWithBoosts: 'Mit {count} Boost(s) starten',
    shield: 'Schild',
    shieldDesc: 'Erster Fehler verziehen',
    biggerZone: 'Größere Zone',
    biggerZoneDesc: 'Erfolgszone +50% größer',
    start20: 'Start +20',
    start20Desc: 'Starte mit 20 Punkten',
    needTicket: '1 Ticket benötigt, um diesen Modus zu spielen',
    ticketsRemaining: '{count} Ticket(s) übrig',
  },
  it: {
    title: 'LUCKY STOP',
    subtitle: 'Tocca nella zona verde al momento giusto!',
    bestScore: 'Miglior Punteggio',
    coins: 'Monete',
    playNow: 'GIOCA ORA',
    gameModes: 'MODALITÀ DI GIOCO',
    shop: 'NEGOZIO',
    dailyChallenges: 'SFIDE GIORNALIERE',
    onlineLeaderboard: 'CLASSIFICA ONLINE',
    theme: 'Tema',
    mode: 'Modalità',
    trapWarning: '⚠️ Attenzione: una delle zone è una trappola. Scegli bene…',
    avoidTrap: 'Evita la zona trappola!',
    trapZone: 'Zona trappola!',
    gifts: 'Regali',
    language: 'Lingua',
    new: 'Nuovo',
    comingSoon: 'Prossimamente',
    comingSoonDesc: 'Nuove funzionalità in arrivo! 🚀',
    settings: 'Impostazioni',
    sound: 'Suono',
    dailyNotifications: 'Notifiche Giornaliere',
    notificationDesc: 'Una notifica al giorno perché la classifica ti aspetta 🎮',
    close: 'Chiudi',
    joinUs: 'Unisciti a noi!',
    socialDesc: 'Segui le novità e partecipa al prossimo concorso per vincere premi esclusivi! 🎁',
    back: 'Indietro',
    backToMenu: 'Torna al Menu',
    username: 'Nome utente',
    noUsername: 'Nessun nome utente',
    global: 'Globale',
    weekly: 'Settimanale',
    refresh: 'Aggiorna',
    offlineMode: 'Modalità offline - Riconnettiti per vedere la classifica',
    noScores: 'Nessun punteggio registrato per questa modalità',
    beFirst: 'Sii il primo a giocare!',
    noWeeklyScores: 'Nessun punteggio questa settimana per questa modalità',
    beFirstWeek: 'Sii il primo a giocare questa settimana!',
    usernameChanged: 'Nome utente modificato',
    usernameChangedDesc: 'Il tuo nuovo nome utente è stato salvato',
    networkError: 'Errore di rete',
    networkErrorDesc: 'Impossibile caricare la classifica',
    shopTitle: 'NEGOZIO',
    shopDesc: 'Sblocca temi, modalità di gioco e potenziamenti',
    themes: 'Temi',
    modes: 'Modalità di Gioco',
    boosts: 'Potenziamenti',
    equipped: 'Equipaggiato',
    owned: 'Posseduto',
    locked: 'Bloccato',
    unlock: 'Sblocca',
    buy: 'Acquista',
    insufficientCoins: 'Monete insufficienti',
    insufficientCoinsDesc: 'Ti servono {amount} monete per acquistare questo.',
    themeLocked: 'Tema bloccato',
    themeLockedDesc: 'Completa 7 giorni di ricompense giornaliere per sbloccare questo tema esclusivo!',
    packBought: 'Pacchetto acquistato!',
    packBoughtDesc: 'Hai ricevuto 4 biglietti per la modalità Esperto!',
    ticketPack: 'Pacchetto Biglietti Esperto',
    ticketPackDesc: '4 biglietti per giocare alla modalità Memoria (Esperto). 1 biglietto = 1 partita.',
    freeCoinsAd: 'Guarda annuncio (80 Monete)',
    watchAdAndGet: 'Guarda un annuncio e ottieni {amount} Monete gratis!',
    adCooldown: 'Nuovo annuncio tra {time}',
    boostShopEmpty: 'I potenziamenti si ottengono tramite sfide e ricompense giornaliere!',
    checkChallenges: 'Vedi Sfide',
    challengesTitle: 'SFIDE DI PROGRESSIONE',
    challengeProgress: 'Progresso sfide',
    totalGamesPlayed: 'Partite totali giocate',
    claimRewards: 'Reclama {count} potenziamento/i',
    reward: 'Ricompensa',
    randomBoost: '1 potenziamento casuale',
    score: 'Punteggio',
    level: 'Livello',
    challengeInfo1: 'Ogni modalità ha 10 livelli di progressione (10, 20, 30... fino a 100 punti)',
    challengeInfo2: 'Raggiungi i livelli per guadagnare monete',
    challengeInfo3: 'Sblocca potenziamenti giocando partite (tutte le modalità combinate)',
    rewardClaimed: 'Ricompensa reclamata!',
    coinsReceived: '{amount} monete aggiunte al tuo account',
    boostsClaimed: 'Potenziamento/i reclamato/i!',
    boostsAdded: '{boosts} aggiunto/i al tuo inventario',
    challengeCompleted: 'Livello raggiunto! 🎉',
    challengeCompletedDesc: '{mode} - Punteggio di {score} raggiunto! Reclama la tua ricompensa nelle Sfide.',
    gamesPlayedReward: '{count} partite giocate! Reclama il tuo potenziamento nelle Sfide.',
    modeSelectionTitle: 'SELEZIONE MODALITÀ',
    currentMode: 'Modalità Attuale',
    gameInProgress: 'Partita in Corso',
    gameInProgressDesc: 'Termina la partita attuale per cambiare modalità.',
    selectMode: 'Scegli Questa Modalità',
    playNowMode: 'Gioca Ora',
    buyInShop: 'Acquista in Negozio',
    duration: 'Durata',
    variableArc: 'Arco variabile',
    mobileZone: 'Zona mobile',
    bestScoreMode: 'Miglior Punteggio',
    modeInfo: 'I migliori punteggi sono salvati separatamente per ogni modalità',
    dailyRewardsTitle: 'RICOMPENSE GIORNALIERE',
    yourStreak: 'La Tua Serie',
    day: 'Giorno',
    days: 'giorni',
    consecutiveDays: 'giorni consecutivi',
    claimReward: 'Reclama',
    comeBackTomorrow: 'Torna domani',
    watchAdForCoins: 'Guarda annuncio per {amount} Monete',
    watchAdDesc: 'Guarda un annuncio e ottieni {amount} Monete gratis!',
    coinsReceivedTitle: 'Monete ricevute!',
    coinsReceivedDesc: 'Hai ricevuto {amount} monete! 🪙',
    rewardClaimedDaily: 'Ricompensa reclamata! 🎉',
    rewardClaimedDailyDesc: 'Hai ricevuto: {reward}',
    cooldownInfo: 'Torna domani per continuare la tua serie!',
    customizationTitle: 'PERSONALIZZAZIONE',
    apply: 'Applica',
    colorPalettes: '🎨 Palette di Colori',
    circles: '⭕ Cerchi',
    effects: '✨ Effetti',
    combo: 'Combo',
    perfect: 'PERFETTO',
    great: 'OTTIMO',
    good: 'BUONO',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'Tocca per iniziare!',
    tapToPlay: 'TOCCA!',
    gameOver: 'GAME OVER',
    finalScore: 'Punteggio Finale',
    newRecord: 'NUOVO RECORD!',
    restart: 'Gioca Ancora',
    mainMenu: 'Menu Principale',
    revive: 'Rivivere',
    watchAdRevive: 'Guarda annuncio',
    reviveSuccess: 'Partita ripresa! 🎮',
    reviveSuccessDesc: 'Puoi continuare a giocare!',
    selectBoosts: 'Seleziona Potenziamenti',
    availableBoosts: 'Potenziamenti Disponibili',
    selectedBoosts: 'Potenziamenti Selezionati',
    noBoostsAvailable: 'Nessun potenziamento disponibile',
    startWithBoosts: 'Inizia con {count} potenziamento/i',
    shield: 'Scudo',
    shieldDesc: 'Primo errore perdonato',
    biggerZone: 'Zona Più Grande',
    biggerZoneDesc: 'Zona di successo +50% più grande',
    start20: 'Inizio +20',
    start20Desc: 'Inizia con 20 punti',
    needTicket: 'Serve 1 biglietto per giocare a questa modalità',
    ticketsRemaining: '{count} biglietto/i rimasto/i',
  },
  pt: {
    title: 'LUCKY STOP',
    subtitle: 'Toque na zona verde no momento certo!',
    bestScore: 'Melhor Pontuação',
    coins: 'Moedas',
    playNow: 'JOGAR AGORA',
    gameModes: 'MODOS DE JOGO',
    shop: 'LOJA',
    dailyChallenges: 'DESAFIOS DIÁRIOS',
    onlineLeaderboard: 'CLASSIFICAÇÃO ONLINE',
    theme: 'Tema',
    mode: 'Modo',
    trapWarning: '⚠️ Atenção: uma das zonas é uma armadilha. Escolha bem…',
    avoidTrap: 'Evite a zona armadilha!',
    trapZone: 'Zona armadilha!',
    gifts: 'Presentes',
    language: 'Idioma',
    new: 'Novo',
    comingSoon: 'Em Breve',
    comingSoonDesc: 'Novos recursos em breve! 🚀',
    settings: 'Configurações',
    sound: 'Som',
    dailyNotifications: 'Notificações Diárias',
    notificationDesc: 'Uma notificação por dia porque a classificação está esperando por você 🎮',
    close: 'Fechar',
    joinUs: 'Junte-se a nós!',
    socialDesc: 'Siga as novidades e participe do próximo concurso para ganhar recompensas exclusivas! 🎁',
    back: 'Voltar',
    backToMenu: 'Voltar ao Menu',
    username: 'Nome de usuário',
    noUsername: 'Sem nome de usuário',
    global: 'Global',
    weekly: 'Semanal',
    refresh: 'Atualizar',
    offlineMode: 'Modo offline - Reconecte para ver a classificação',
    noScores: 'Nenhuma pontuação registrada para este modo',
    beFirst: 'Seja o primeiro a jogar!',
    noWeeklyScores: 'Nenhuma pontuação esta semana para este modo',
    beFirstWeek: 'Seja o primeiro a jogar esta semana!',
    usernameChanged: 'Nome de usuário alterado',
    usernameChangedDesc: 'Seu novo nome de usuário foi salvo',
    networkError: 'Erro de rede',
    networkErrorDesc: 'Não é possível carregar a classificação',
    shopTitle: 'LOJA',
    shopDesc: 'Desbloqueie temas, modos de jogo e reforços',
    themes: 'Temas',
    modes: 'Modos de Jogo',
    boosts: 'Reforços',
    equipped: 'Equipado',
    owned: 'Possuído',
    locked: 'Bloqueado',
    unlock: 'Desbloquear',
    buy: 'Comprar',
    insufficientCoins: 'Moedas insuficientes',
    insufficientCoinsDesc: 'Você precisa de {amount} moedas para comprar isso.',
    themeLocked: 'Tema bloqueado',
    themeLockedDesc: 'Complete 7 dias de recompensas diárias para desbloquear este tema exclusivo!',
    packBought: 'Pacote comprado!',
    packBoughtDesc: 'Você recebeu 4 tickets para o modo Especialista!',
    ticketPack: 'Pacote de Tickets Especialista',
    ticketPackDesc: '4 tickets para jogar o modo Memória (Especialista). 1 ticket = 1 jogo.',
    freeCoinsAd: 'Assistir anúncio (80 Moedas)',
    watchAdAndGet: 'Assista a um anúncio e ganhe {amount} Moedas grátis!',
    adCooldown: 'Novo anúncio em {time}',
    boostShopEmpty: 'Reforços são obtidos através de desafios e recompensas diárias!',
    checkChallenges: 'Ver Desafios',
    challengesTitle: 'DESAFIOS DE PROGRESSÃO',
    challengeProgress: 'Progresso dos desafios',
    totalGamesPlayed: 'Total de jogos jogados',
    claimRewards: 'Reivindicar {count} reforço(s)',
    reward: 'Recompensa',
    randomBoost: '1 reforço aleatório',
    score: 'Pontuação',
    level: 'Nível',
    challengeInfo1: 'Cada modo tem 10 níveis de progressão (10, 20, 30... até 100 pontos)',
    challengeInfo2: 'Alcance níveis para ganhar moedas',
    challengeInfo3: 'Desbloqueie reforços jogando jogos (todos os modos combinados)',
    rewardClaimed: 'Recompensa reivindicada!',
    coinsReceived: '{amount} moedas adicionadas à sua conta',
    boostsClaimed: 'Reforço(s) reivindicado(s)!',
    boostsAdded: '{boosts} adicionado(s) ao seu inventário',
    challengeCompleted: 'Nível alcançado! 🎉',
    challengeCompletedDesc: '{mode} - Pontuação de {score} alcançada! Reivindique sua recompensa nos Desafios.',
    gamesPlayedReward: '{count} jogos jogados! Reivindique seu reforço nos Desafios.',
    modeSelectionTitle: 'SELEÇÃO DE MODO',
    currentMode: 'Modo Atual',
    gameInProgress: 'Jogo em Andamento',
    gameInProgressDesc: 'Termine seu jogo atual para mudar de modo.',
    selectMode: 'Escolher Este Modo',
    playNowMode: 'Jogar Agora',
    buyInShop: 'Comprar na Loja',
    duration: 'Duração',
    variableArc: 'Arco variável',
    mobileZone: 'Zona móvel',
    bestScoreMode: 'Melhor Pontuação',
    modeInfo: 'As melhores pontuações são salvas separadamente para cada modo',
    dailyRewardsTitle: 'RECOMPENSAS DIÁRIAS',
    yourStreak: 'Sua Sequência',
    day: 'Dia',
    days: 'dias',
    consecutiveDays: 'dias consecutivos',
    claimReward: 'Reivindicar',
    comeBackTomorrow: 'Volte amanhã',
    watchAdForCoins: 'Assistir anúncio por {amount} Moedas',
    watchAdDesc: 'Assista a um anúncio e ganhe {amount} Moedas grátis!',
    coinsReceivedTitle: 'Moedas recebidas!',
    coinsReceivedDesc: 'Você recebeu {amount} moedas! 🪙',
    rewardClaimedDaily: 'Recompensa reivindicada! 🎉',
    rewardClaimedDailyDesc: 'Você recebeu: {reward}',
    cooldownInfo: 'Volte amanhã para continuar sua sequência!',
    customizationTitle: 'PERSONALIZAÇÃO',
    apply: 'Aplicar',
    colorPalettes: '🎨 Paletas de Cores',
    circles: '⭕ Círculos',
    effects: '✨ Efeitos',
    combo: 'Combo',
    perfect: 'PERFEITO',
    great: 'ÓTIMO',
    good: 'BOM',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'Toque para começar!',
    tapToPlay: 'TOQUE!',
    gameOver: 'GAME OVER',
    finalScore: 'Pontuação Final',
    newRecord: 'NOVO RECORDE!',
    restart: 'Jogar Novamente',
    mainMenu: 'Menu Principal',
    revive: 'Reviver',
    watchAdRevive: 'Assistir anúncio',
    reviveSuccess: 'Jogo revivido! 🎮',
    reviveSuccessDesc: 'Você pode continuar jogando!',
    selectBoosts: 'Selecionar Reforços',
    availableBoosts: 'Reforços Disponíveis',
    selectedBoosts: 'Reforços Selecionados',
    noBoostsAvailable: 'Nenhum reforço disponível',
    startWithBoosts: 'Começar com {count} reforço(s)',
    shield: 'Escudo',
    shieldDesc: 'Primeiro erro perdoado',
    biggerZone: 'Zona Maior',
    biggerZoneDesc: 'Zona de sucesso +50% maior',
    start20: 'Início +20',
    start20Desc: 'Comece com 20 pontos',
    needTicket: 'Precisa de 1 ticket para jogar este modo',
    ticketsRemaining: '{count} ticket(s) restante(s)',
  },
  ar: {
    title: 'LUCKY STOP',
    subtitle: '!انقر في المنطقة الخضراء في الوقت المناسب',
    bestScore: 'أفضل نتيجة',
    coins: 'عملات',
    playNow: 'العب الآن',
    gameModes: 'أوضاع اللعب',
    shop: 'المتجر',
    dailyChallenges: 'التحديات اليومية',
    onlineLeaderboard: 'لوحة الصدارة',
    theme: 'السمة',
    mode: 'الوضع',
    trapWarning: '⚠️ تحذير: إحدى المناطق فخ. اختر بحكمة…',
    avoidTrap: '!تجنب منطقة الفخ',
    trapZone: '!منطقة الفخ',
    gifts: 'هدايا',
    language: 'اللغة',
    new: 'جديد',
    comingSoon: 'قريباً',
    comingSoonDesc: '!ميزات جديدة قريباً 🚀',
    settings: 'الإعدادات',
    sound: 'الصوت',
    dailyNotifications: 'الإشعارات اليومية',
    notificationDesc: 'إشعار واحد في اليوم لأن لوحة الصدارة في انتظارك 🎮',
    close: 'إغلاق',
    joinUs: '!انضم إلينا',
    socialDesc: '!تابع الأخبار وشارك في المسابقة القادمة للفوز بمكافآت حصرية 🎁',
    back: 'رجوع',
    backToMenu: 'العودة إلى القائمة',
    username: 'اسم المستخدم',
    noUsername: 'لا يوجد اسم مستخدم',
    global: 'عالمي',
    weekly: 'أسبوعي',
    refresh: 'تحديث',
    offlineMode: 'وضع عدم الاتصال - أعد الاتصال لرؤية لوحة الصدارة',
    noScores: 'لا توجد نتائج مسجلة لهذا الوضع',
    beFirst: '!كن أول من يلعب',
    noWeeklyScores: 'لا توجد نتائج هذا الأسبوع لهذا الوضع',
    beFirstWeek: '!كن أول من يلعب هذا الأسبوع',
    usernameChanged: 'تم تغيير اسم المستخدم',
    usernameChangedDesc: 'تم حفظ اسم المستخدم الجديد',
    networkError: 'خطأ في الشبكة',
    networkErrorDesc: 'تعذر تحميل لوحة الصدارة',
    shopTitle: 'المتجر',
    shopDesc: 'افتح المواضيع وأوضاع اللعب والتعزيزات',
    themes: 'المواضيع',
    modes: 'أوضاع اللعب',
    boosts: 'التعزيزات',
    equipped: 'مجهز',
    owned: 'مملوك',
    locked: 'مقفل',
    unlock: 'فتح',
    buy: 'شراء',
    insufficientCoins: 'عملات غير كافية',
    insufficientCoinsDesc: '.تحتاج إلى {amount} عملة لشراء هذا',
    themeLocked: 'السمة مقفلة',
    themeLockedDesc: '!أكمل 7 أيام من المكافآت اليومية لفتح هذه السمة الحصرية',
    packBought: '!تم شراء الحزمة',
    packBoughtDesc: '!تلقيت 4 تذاكر لوضع الخبير',
    ticketPack: 'حزمة تذاكر الخبير',
    ticketPackDesc: '.4 تذاكر للعب وضع الذاكرة (خبير). 1 تذكرة = 1 لعبة',
    freeCoinsAd: '(عملة 80) مشاهدة إعلان',
    watchAdAndGet: '!شاهد إعلانًا واحصل على {amount} عملة مجانًا',
    adCooldown: 'إعلان جديد في {time}',
    boostShopEmpty: '!يتم الحصول على التعزيزات من خلال التحديات والمكافآت اليومية',
    checkChallenges: 'عرض التحديات',
    challengesTitle: 'تحديات التقدم',
    challengeProgress: 'تقدم التحديات',
    totalGamesPlayed: 'إجمالي الألعاب الملعوبة',
    claimRewards: 'المطالبة بـ {count} تعزيز(ات)',
    reward: 'مكافأة',
    randomBoost: 'تعزيز عشوائي 1',
    score: 'النتيجة',
    level: 'المستوى',
    challengeInfo1: 'نقطة) 100... و 30 و 20 و 10( كل وضع له 10 مستويات تقدم',
    challengeInfo2: 'الوصول إلى المستويات لكسب العملات',
    challengeInfo3: '(افتح التعزيزات بلعب الألعاب (جميع الأوضاع مجتمعة',
    rewardClaimed: '!تمت المطالبة بالمكافأة',
    coinsReceived: 'تمت إضافة {amount} عملة إلى حسابك',
    boostsClaimed: '!تمت المطالبة بالتعزيز(ات)',
    boostsAdded: 'تمت إضافة {boosts} إلى مخزونك',
    challengeCompleted: '!تم الوصول إلى المستوى 🎉',
    challengeCompletedDesc: '.تم الوصول إلى نتيجة {score} - {mode}! اطلب مكافأتك في التحديات',
    gamesPlayedReward: '!ألعاب ملعوبة {count}! اطلب تعزيزك في التحديات',
    modeSelectionTitle: 'اختيار الوضع',
    currentMode: 'الوضع الحالي',
    gameInProgress: 'لعبة قيد التشغيل',
    gameInProgressDesc: '.أنه لعبتك الحالية لتغيير الوضع',
    selectMode: 'اختر هذا الوضع',
    playNowMode: 'العب الآن',
    buyInShop: 'الشراء من المتجر',
    duration: 'المدة',
    variableArc: 'قوس متغير',
    mobileZone: 'منطقة متحركة',
    bestScoreMode: 'أفضل نتيجة',
    modeInfo: 'يتم حفظ أفضل النتائج بشكل منفصل لكل وضع',
    dailyRewardsTitle: 'المكافآت اليومية',
    yourStreak: 'سلسلتك',
    day: 'يوم',
    days: 'أيام',
    consecutiveDays: 'أيام متتالية',
    claimReward: 'المطالبة',
    comeBackTomorrow: 'عد غدًا',
    watchAdForCoins: 'مشاهدة إعلان مقابل {amount} عملة',
    watchAdDesc: '!شاهد إعلانًا واحصل على {amount} عملة مجانًا',
    coinsReceivedTitle: '!تم استلام العملات',
    coinsReceivedDesc: '!تلقيت {amount} عملة 🪙',
    rewardClaimedDaily: '!تمت المطالبة بالمكافأة 🎉',
    rewardClaimedDailyDesc: 'تلقيت: {reward}',
    cooldownInfo: '!عد غدًا لمواصلة سلسلتك',
    customizationTitle: 'التخصيص',
    apply: 'تطبيق',
    colorPalettes: '🎨 لوحات الألوان',
    circles: '⭕ دوائر',
    effects: '✨ تأثيرات',
    combo: 'كومبو',
    perfect: 'مثالي',
    great: 'رائع',
    good: 'جيد',
    readyTitle: 'LUCKY STOP',
    readySubtitle: '!انقر للبدء',
    tapToPlay: '!انقر',
    gameOver: 'انتهت اللعبة',
    finalScore: 'النتيجة النهائية',
    newRecord: '!رقم قياسي جديد',
    restart: 'العب مرة أخرى',
    mainMenu: 'القائمة الرئيسية',
    revive: 'إحياء',
    watchAdRevive: 'مشاهدة إعلان',
    reviveSuccess: '!تم إحياء اللعبة 🎮',
    reviveSuccessDesc: '!يمكنك الاستمرار في اللعب',
    selectBoosts: 'حدد التعزيزات',
    availableBoosts: 'التعزيزات المتاحة',
    selectedBoosts: 'التعزيزات المحددة',
    noBoostsAvailable: 'لا توجد تعزيزات متاحة',
    startWithBoosts: 'ابدأ بـ {count} تعزيز(ات)',
    shield: 'درع',
    shieldDesc: 'الخطأ الأول مسامح',
    biggerZone: 'منطقة أكبر',
    biggerZoneDesc: 'منطقة النجاح +50٪ أكبر',
    start20: 'بداية +20',
    start20Desc: 'ابدأ بـ 20 نقطة',
    needTicket: 'تحتاج إلى تذكرة واحدة للعب هذا الوضع',
    ticketsRemaining: '{count} تذكرة (تذاكر) متبقية',
  },
  ja: {
    title: 'LUCKY STOP',
    subtitle: '緑のゾーンを適切なタイミングでタップ！',
    bestScore: 'ベストスコア',
    coins: 'コイン',
    playNow: '今すぐプレイ',
    gameModes: 'ゲームモード',
    shop: 'ショップ',
    dailyChallenges: '日替わりチャレンジ',
    onlineLeaderboard: 'オンラインランキング',
    theme: 'テーマ',
    mode: 'モード',
    trapWarning: '⚠️ 警告：ゾーンの1つはトラップです。賢く選択してください…',
    avoidTrap: 'トラップゾーンを避けてください！',
    trapZone: 'トラップゾーン！',
    gifts: 'ギフト',
    language: '言語',
    new: '新着',
    comingSoon: '近日公開',
    comingSoonDesc: '新機能が近日公開！🚀',
    settings: '設定',
    sound: 'サウンド',
    dailyNotifications: '毎日の通知',
    notificationDesc: 'ランキングがあなたを待っているので1日1回通知 🎮',
    close: '閉じる',
    joinUs: '参加しよう！',
    socialDesc: 'ニュースをフォローして、次のコンテストに参加して限定報酬を獲得しよう！🎁',
    back: '戻る',
    backToMenu: 'メニューに戻る',
    username: 'ユーザー名',
    noUsername: 'ユーザー名なし',
    global: 'グローバル',
    weekly: 'ウィークリー',
    refresh: '更新',
    offlineMode: 'オフラインモード - 再接続してランキングを表示',
    noScores: 'このモードのスコアはありません',
    beFirst: '最初にプレイしよう！',
    noWeeklyScores: '今週このモードのスコアはありません',
    beFirstWeek: '今週最初にプレイしよう！',
    usernameChanged: 'ユーザー名を変更しました',
    usernameChangedDesc: '新しいユーザー名が保存されました',
    networkError: 'ネットワークエラー',
    networkErrorDesc: 'ランキングを読み込めません',
    shopTitle: 'ショップ',
    shopDesc: 'テーマ、ゲームモード、ブーストをアンロック',
    themes: 'テーマ',
    modes: 'ゲームモード',
    boosts: 'ブースト',
    equipped: '装備中',
    owned: '所有済み',
    locked: 'ロック中',
    unlock: 'アンロック',
    buy: '購入',
    insufficientCoins: 'コイン不足',
    insufficientCoinsDesc: 'これを購入するには{amount}コインが必要です。',
    themeLocked: 'テーマがロックされています',
    themeLockedDesc: '7日間の日替わり報酬を完了して、この限定テーマをアンロックしてください！',
    packBought: 'パック購入完了！',
    packBoughtDesc: 'エキスパートモード用のチケットを4枚受け取りました！',
    ticketPack: 'エキスパートチケットパック',
    ticketPackDesc: 'メモリー（エキスパート）モードをプレイするためのチケット4枚。1チケット=1ゲーム。',
    freeCoinsAd: '広告を見る（80コイン）',
    watchAdAndGet: '広告を見て{amount}コインを無料で獲得！',
    adCooldown: '新しい広告まで{time}',
    boostShopEmpty: 'ブーストはチャレンジとデイリー報酬から獲得できます！',
    checkChallenges: 'チャレンジを見る',
    challengesTitle: '進行チャレンジ',
    challengeProgress: 'チャレンジ進行状況',
    totalGamesPlayed: 'プレイした総ゲーム数',
    claimRewards: '{count}ブーストを獲得',
    reward: '報酬',
    randomBoost: 'ランダムブースト1個',
    score: 'スコア',
    level: 'レベル',
    challengeInfo1: '各モードには10の進行レベルがあります（10、20、30...100ポイントまで）',
    challengeInfo2: 'レベルに到達してコインを獲得',
    challengeInfo3: 'ゲームをプレイしてブーストをアンロック（全モード合計）',
    rewardClaimed: '報酬を獲得しました！',
    coinsReceived: '{amount}コインがアカウントに追加されました',
    boostsClaimed: 'ブーストを獲得しました！',
    boostsAdded: '{boosts}がインベントリに追加されました',
    challengeCompleted: 'レベル到達！🎉',
    challengeCompletedDesc: '{mode} - {score}スコア到達！チャレンジで報酬を獲得してください。',
    gamesPlayedReward: '{count}ゲームプレイ！チャレンジでブーストを獲得してください。',
    modeSelectionTitle: 'モード選択',
    currentMode: '現在のモード',
    gameInProgress: 'ゲーム進行中',
    gameInProgressDesc: 'モードを変更するには現在のゲームを終了してください。',
    selectMode: 'このモードを選択',
    playNowMode: '今すぐプレイ',
    buyInShop: 'ショップで購入',
    duration: '期間',
    variableArc: '可変アーク',
    mobileZone: '移動ゾーン',
    bestScoreMode: 'ベストスコア',
    modeInfo: 'ベストスコアは各モードごとに個別に保存されます',
    dailyRewardsTitle: 'デイリー報酬',
    yourStreak: 'あなたの連続記録',
    day: '日',
    days: '日間',
    consecutiveDays: '連続日数',
    claimReward: '獲得',
    comeBackTomorrow: '明日また来てください',
    watchAdForCoins: '広告を見て{amount}コイン獲得',
    watchAdDesc: '広告を見て{amount}コインを無料で獲得！',
    coinsReceivedTitle: 'コイン受け取り！',
    coinsReceivedDesc: '{amount}コインを受け取りました！🪙',
    rewardClaimedDaily: '報酬を獲得しました！🎉',
    rewardClaimedDailyDesc: '受け取りました：{reward}',
    cooldownInfo: '明日また来て連続記録を続けてください！',
    customizationTitle: 'カスタマイズ',
    apply: '適用',
    colorPalettes: '🎨 カラーパレット',
    circles: '⭕ サークル',
    effects: '✨ エフェクト',
    combo: 'コンボ',
    perfect: 'パーフェクト',
    great: '素晴らしい',
    good: '良い',
    readyTitle: 'LUCKY STOP',
    readySubtitle: 'タップして開始！',
    tapToPlay: 'タップ！',
    gameOver: 'ゲームオーバー',
    finalScore: '最終スコア',
    newRecord: '新記録！',
    restart: 'もう一度プレイ',
    mainMenu: 'メインメニュー',
    revive: '復活',
    watchAdRevive: '広告を見る',
    reviveSuccess: 'ゲーム復活！🎮',
    reviveSuccessDesc: 'プレイを続けられます！',
    selectBoosts: 'ブースト選択',
    availableBoosts: '利用可能なブースト',
    selectedBoosts: '選択されたブースト',
    noBoostsAvailable: 'ブーストがありません',
    startWithBoosts: '{count}ブーストでスタート',
    shield: 'シールド',
    shieldDesc: '最初のミスが許される',
    biggerZone: '拡大ゾーン',
    biggerZoneDesc: '成功ゾーンが+50%大きくなる',
    start20: 'スタート+20',
    start20Desc: '20ポイントでスタート',
    needTicket: 'このモードをプレイするにはチケットが1枚必要です',
    ticketsRemaining: '残りチケット{count}枚',
  },
  zh: {
    title: 'LUCKY STOP',
    subtitle: '在正确的时间点击绿色区域！',
    bestScore: '最高分',
    coins: '金币',
    playNow: '立即游戏',
    gameModes: '游戏模式',
    shop: '商店',
    dailyChallenges: '每日挑战',
    onlineLeaderboard: '在线排行榜',
    theme: '主题',
    mode: '模式',
    trapWarning: '⚠️ 警告：其中一个区域是陷阱。明智选择…',
    avoidTrap: '避开陷阱区域！',
    trapZone: '陷阱区域！',
    gifts: '礼物',
    language: '语言',
    new: '新功能',
    comingSoon: '即将推出',
    comingSoonDesc: '新功能即将推出！🚀',
    settings: '设置',
    sound: '声音',
    dailyNotifications: '每日通知',
    notificationDesc: '每天一个通知，因为排行榜在等你 🎮',
    close: '关闭',
    joinUs: '加入我们！',
    socialDesc: '关注新闻并参加下一场比赛以赢取独家奖励！🎁',
    back: '返回',
    backToMenu: '返回菜单',
    username: '用户名',
    noUsername: '无用户名',
    global: '全球',
    weekly: '每周',
    refresh: '刷新',
    offlineMode: '离线模式 - 重新连接以查看排行榜',
    noScores: '此模式没有记录分数',
    beFirst: '成为第一个玩的人！',
    noWeeklyScores: '本周此模式没有分数',
    beFirstWeek: '成为本周第一个玩的人！',
    usernameChanged: '用户名已更改',
    usernameChangedDesc: '您的新用户名已保存',
    networkError: '网络错误',
    networkErrorDesc: '无法加载排行榜',
    shopTitle: '商店',
    shopDesc: '解锁主题、游戏模式和增强',
    themes: '主题',
    modes: '游戏模式',
    boosts: '增强',
    equipped: '已装备',
    owned: '已拥有',
    locked: '已锁定',
    unlock: '解锁',
    buy: '购买',
    insufficientCoins: '金币不足',
    insufficientCoinsDesc: '您需要{amount}金币来购买此物品。',
    themeLocked: '主题已锁定',
    themeLockedDesc: '完成7天的每日奖励以解锁此专属主题！',
    packBought: '购买成功！',
    packBoughtDesc: '您获得了4张专家模式门票！',
    ticketPack: '专家门票包',
    ticketPackDesc: '4张门票用于游玩记忆（专家）模式。1张门票=1局游戏。',
    freeCoinsAd: '观看广告（80金币）',
    watchAdAndGet: '观看广告并免费获得{amount}金币！',
    adCooldown: '{time}后新广告',
    boostShopEmpty: '增强通过挑战和每日奖励获得！',
    checkChallenges: '查看挑战',
    challengesTitle: '进度挑战',
    challengeProgress: '挑战进度',
    totalGamesPlayed: '总游戏次数',
    claimRewards: '领取{count}个增强',
    reward: '奖励',
    randomBoost: '1个随机增强',
    score: '分数',
    level: '等级',
    challengeInfo1: '每个模式有10个进度等级（10、20、30...直到100分）',
    challengeInfo2: '达到等级以赚取金币',
    challengeInfo3: '通过玩游戏解锁增强（所有模式组合）',
    rewardClaimed: '已领取奖励！',
    coinsReceived: '{amount}金币已添加到您的账户',
    boostsClaimed: '已领取增强！',
    boostsAdded: '{boosts}已添加到您的库存',
    challengeCompleted: '等级达成！🎉',
    challengeCompletedDesc: '{mode} - 达到{score}分！在挑战中领取您的奖励。',
    gamesPlayedReward: '已玩{count}局！在挑战中领取您的增强。',
    modeSelectionTitle: '模式选择',
    currentMode: '当前模式',
    gameInProgress: '游戏进行中',
    gameInProgressDesc: '完成当前游戏以切换模式。',
    selectMode: '选择此模式',
    playNowMode: '立即游玩',
    buyInShop: '在商店购买',
    duration: '持续时间',
    variableArc: '可变弧',
    mobileZone: '移动区域',
    bestScoreMode: '最高分',
    modeInfo: '最佳分数为每个模式单独保存',
    dailyRewardsTitle: '每日奖励',
    yourStreak: '您的连续记录',
    day: '天',
    days: '天',
    consecutiveDays: '连续天数',
    claimReward: '领取',
    comeBackTomorrow: '明天再来',
    watchAdForCoins: '观看广告获得{amount}金币',
    watchAdDesc: '观看广告并免费获得{amount}金币！',
    coinsReceivedTitle: '已收到金币！',
    coinsReceivedDesc: '您收到了{amount}金币！🪙',
    rewardClaimedDaily: '已领取奖励！🎉',
    rewardClaimedDailyDesc: '您收到了：{reward}',
    cooldownInfo: '明天再来继续您的连续记录！',
    customizationTitle: '自定义',
    apply: '应用',
    colorPalettes: '🎨 调色板',
    circles: '⭕ 圆圈',
    effects: '✨ 效果',
    combo: '连击',
    perfect: '完美',
    great: '优秀',
    good: '良好',
    readyTitle: 'LUCKY STOP',
    readySubtitle: '点击开始！',
    tapToPlay: '点击！',
    gameOver: '游戏结束',
    finalScore: '最终分数',
    newRecord: '新纪录！',
    restart: '再玩一次',
    mainMenu: '主菜单',
    revive: '复活',
    watchAdRevive: '观看广告',
    reviveSuccess: '游戏复活！🎮',
    reviveSuccessDesc: '您可以继续游玩！',
    selectBoosts: '选择增强',
    availableBoosts: '可用增强',
    selectedBoosts: '已选增强',
    noBoostsAvailable: '没有可用增强',
    startWithBoosts: '以{count}个增强开始',
    shield: '护盾',
    shieldDesc: '第一个错误被原谅',
    biggerZone: '扩大区域',
    biggerZoneDesc: '成功区域+50%更大',
    start20: '开始+20',
    start20Desc: '以20分开始',
    needTicket: '需要1张门票来玩此模式',
    ticketsRemaining: '剩余{count}张门票',
  },
};
